force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Last_Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Last_Session_Date__c</fullName>
    <label>Last Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <isActive>false</isActive>
                <label>Abandoned</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
                <isActive>false</isActive>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Fixed_Billing__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Billing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Charge a fixed &apos;Amount&apos; if this field is checked.</description>
    <inlineHelpText>Charge a fixed &apos;Amount&apos; if this field is checked.</inlineHelpText>
    <label>Fixed Billing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applies GST if checked.</description>
    <inlineHelpText>Applies GST if checked.</inlineHelpText>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Prorate__c.field-meta.xml
<CustomField>
    <fullName>Prorate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Applicable only for tuition fee.</inlineHelpText>
    <label>Prorate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price Per Session.</description>
    <inlineHelpText>Price Per Session.</inlineHelpText>
    <label>Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Number of Units</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer invoice line items(child records of invoice)</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>to store amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store fee details</description>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>to store related invoice details</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store subscription line item</description>
    <label>Subscription Line Item</label>
    <referenceTo>Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <description>Date on which the Session will occur.</description>
    <inlineHelpText>Date on which the Session will occur.</inlineHelpText>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer subscription line items(child records of subscription)</description>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>SUB-ITEM-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>to store amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to hold enrollment number</description>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store parent fee detail if it is tution fee</description>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Fee__c.Type__c</field>
            <operation>equals</operation>
            <value>Tuition Fee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Next_Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Bill_Date__c</fullName>
    <description>to hold next bill date</description>
    <label>Next Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to hold status of subscription line item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Suspended</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Start_Date__c</fullName>
    <description>to store start date of subscription line item</description>
    <label>Subscription Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/MonthlyFullInvoiceHandler.cls
public class MonthlyFullInvoiceHandler extends iBlufyInvoiceEngine {
    
    // public Subscription_Line_Item__c objLineItem;
    public MonthlyFullInvoiceHandler(Subscription_Line_Item__c objLineItem){
        this.objLineItem = objLineItem;
    }
    
    public override List<Invoice_Line_Item__c> createInvoiceLineItems(Invoice__c objInv,LineItemCalculateWrapper objWrap,String year, String month){
        List<Invoice_Line_Item__c> listOfLineItems = new List<Invoice_Line_Item__c>();
        Integer noOfSession = 0;
        List<Session__c> sessions = objWrap.mapOfClassSession.containsKey(objLineItem.Enrollment__r.Class_Session__c) ?  
        objWrap.mapOfClassSession.get(objLineItem.Enrollment__r.Class_Session__c) : new List<Session__c>();
        Decimal amount = 0;
        date dateObj = date.today();
        if(Integer.valueOf(month) != dateObj.month() && String.isNotBlank(year) && String.isNotBlank(month)){
             dateObj = date.newinstance(Integer.valueOf(year), Integer.valueOf(month), 1);
        }
        system.debug('dateObj'+dateObj);
        system.debug('objLineItem.Fee__r.Fixed_Billing__c  '+objLineItem.Fee__r.Fixed_Billing__c);
        system.debug('objLineItem.Fee__r.Prorate__c  '+ objLineItem.Fee__r.Prorate__c);
        system.debug('objLineItemId-'+objLineItem.Id);
        system.debug('sessions-size '+sessions.size());
        if(objLineItem.Fee__r.Fixed_Billing__c != false && objLineItem.Fee__r.Prorate__c == false){
            amount = objLineItem.Fee__r.amount__c;
        }else {
            if(objLineItem.Enrollment__r.Start_Date__c != null && objLineItem.Enrollment__r.Last_Session_Date__c != null
              && objLineItem.Enrollment__r.Start_Date__c.month() == dateObj.month() && objLineItem.Enrollment__r.Last_Session_Date__c.month() == dateObj.month()){
                for(Session__c session : sessions){
                    if(session.session_Date__c.month() == dateObj.month() && session.session_Date__c >= objLineItem.Enrollment__r.Start_Date__c && session.session_Date__c <= objLineItem.Enrollment__r.Last_Session_Date__c){
                        noOfSession+=1;
                    }
                }
            }else if(objLineItem.Enrollment__r.Start_Date__c != null && objLineItem.Enrollment__r.Start_Date__c.month() == dateObj.month()){
                for(Session__c session : sessions){
                    if(session.session_Date__c.month() == dateObj.month() && session.session_Date__c >= objLineItem.Enrollment__r.Start_Date__c ){
                        noOfSession+=1;
                    }
                }
            }else if(objLineItem.Enrollment__r.Last_Session_Date__c != null &&  objLineItem.Enrollment__r.Last_Session_Date__c.month() == dateObj.month()){
                for(Session__c session : sessions){
                    if(session.session_Date__c.month() == dateObj.month() && session.session_Date__c <= objLineItem.Enrollment__r.Last_Session_Date__c ){
                        noOfSession+=1;
                    }
                }
            }else{
                for(Session__c session : sessions){
                    system.debug('session month ' + session.session_Date__c.month());
                    if(session.session_Date__c.month() == dateObj.month()){
                        noOfSession+=1;
                    }
                }
            } 
            system.debug('noOfSession'+noOfSession);           
            if(objLineItem.Fee__r.Unit_Price__c != null){
                amount = noOfSession * objLineItem.Fee__r.Unit_Price__c;
            }           
            system.debug('amount'+amount);
        }
        // if(objLineItem.Subscription_Start_Date__c != NULL && objLineItem.Subscription_Start_Date__c.month() == objLineItem.Next_Bill_Date__c.month() 
        //    && objLineItem.Subscription_Start_Date__c.year() == objLineItem.Next_Bill_Date__c.year()){
        //        System.debug('inside subscription is starting late in month');
        //        for(Session__c session : sessions){
        //            if(session.session_Date__c >= objLineItem.Subscription_Start_Date__c ){
        //                noOfSession+=1;
        //            }
        //        }
        //    }else if(objLineItem.Enrollment__r.Last_Session_Date__c != NULL && objLineItem.Enrollment__r.Last_Session_Date__c.month() == objLineItem.Next_Bill_Date__c.month() 
        //             && objLineItem.Enrollment__r.Last_Session_Date__c.year() == objLineItem.Next_Bill_Date__c.year()){
        //                 System.debug('inside subscription is ending in month');
        //                 for(Session__c session : sessions){
        //                     if(session.session_Date__c <= objLineItem.Enrollment__r.Last_Session_Date__c ){
        //                         noOfSession+=1;
        //                     }
        //                 } 
        //                 objLineItem.put('Status__c','InActive');
        //                 //objLineItem.Status__c = 'InActive';
        //             }else{
        //                 noOfSession = sessions.size();
        //             }
        //Added by Asif on 09-10-20 if number of session is greater than number of units, put number of units in the noOfSession
        if(objLineItem.Fee__r.Units__c != null && objLineItem.Fee__r.Units__c > 0 && noOfSession > objLineItem.Fee__r.Units__c){
            noOfSession = Integer.valueOf(objLineItem.Fee__r.Units__c);
        }
       
        /*if(objLineItem.Fee__r.Fixed_Billing__c != false){
            amount = objLineItem.Fee__r.amount__c;
        }else {
            amount = noOfSession * objLineItem.Fee__r.Unit_Price__c;
        }*/
        //Decimal amount = noOfSession * objLineItem.Fee__r.Unit_Price__c;
        system.debug('objLineItem'+objLineItem.Fee__r.GST_Applicable__c);
        Invoice_Line_Item__c objInvoiceItem = InvoiceFactory.createInvLineItem(objLineItem,'Fee',amount,objInv.id,year,month);  //new Invoice_Line_Item__c();
        listOfLineItems.add(objInvoiceItem);
        
        // set next bill date
      //  objLineItem.put('Next_Bill_Date__c',date.valueOf(objLineItem.Next_Bill_Date__c.addMonths(1))); 
        system.debug('MONTHLY'+objLineItem);
        //objLineItem.Next_Bill_Date__c = objLineItem.Next_Bill_Date__c.addMonths(1);
        return listOfLineItems;
    }
}