force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Term__c/Class_Term__c.object-meta.xml
<CustomObject>
    <label>Class Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Term__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Terms</relationshipLabel>
    <relationshipName>Class_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class_Term__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Term</label>
    <referenceTo>Term__c</referenceTo>
    <relationshipLabel>Class Terms</relationshipLabel>
    <relationshipName>Class_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>to store account details if record type is customer</description>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice (Customer)</relationshipLabel>
    <relationshipName>Invoice_Customer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store subscription details</description>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Invoice</relationshipLabel>
    <relationshipName>Invoice</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer invoice line items(child records of invoice)</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>to store related invoice details</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Subscription_Line_Item__c.field-meta.xml
<CustomField>
    <fullName>Subscription_Line_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store subscription line item</description>
    <label>Subscription Line Item</label>
    <referenceTo>Subscription_Line_Item__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class associated with this Session.</description>
    <inlineHelpText>Class associated with this Session.</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Class_Term__c.field-meta.xml
<CustomField>
    <fullName>Class_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class Term associated with this Session.</description>
    <inlineHelpText>Class Term associated with this Session.</inlineHelpText>
    <label>Class Term</label>
    <referenceTo>Class_Term__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <description>Date on which the Session will occur.</description>
    <inlineHelpText>Date on which the Session will occur.</inlineHelpText>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Subscription__c/Subscription__c.object-meta.xml
<CustomObject>
    <description>subscription details of the customer</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c/fields/Payment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Payment_Frequency__c</fullName>
    <description>to hold how frequent customer will make payment</description>
    <label>Payment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Term</fullName>
            </value>
            <value>
                <fullName>One-time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/Subscription_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer subscription line items(child records of subscription)</description>
    <label>Subscription Line Item</label>
    <nameField>
        <displayFormat>SUB-ITEM-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Class_Term__c.field-meta.xml
<CustomField>
    <fullName>Class_Term__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It will help invoice engine to charge proper amount</description>
    <label>Class Term</label>
    <referenceTo>Class_Term__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to hold enrollment number</description>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store parent fee detail if it is tution fee</description>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Fee__c.Type__c</field>
            <operation>equals</operation>
            <value>Tuition Fee</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Subscription_Line_Item__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <description>to hold details of parent subscription</description>
    <label>Subscription</label>
    <referenceTo>Subscription__c</referenceTo>
    <relationshipLabel>Subscription Line Items</relationshipLabel>
    <relationshipName>Subscription_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/InvoiceFactory.cls
/*
Name            :   InvoiceFactory
Date            :   03/23/2020
Author          :   Arpit vijayvergiya
Description     :   This class acts as midileware which takes will decide right invoice handler.
*/
public class InvoiceFactory {
    /*
As per blufy model , a subscription can have multiple subscription line item so, each line item can fall down into different
Invoice handler.
*/
    public List<iBlufyInvoiceEngine> listOfInvoiceHandler;
    public Set<String> setOFClassSessionIds;
    public Invoice__c objInv;
    public Subscription__c objSub;
    private Date executionDate;
    
    public InvoiceFactory (Subscription__c sub , Date executionDate/*, Term__c nextTerm, Date nextMonthStartDate*/){
        this.objSub = sub;
        this.executionDate = executionDate;
        listOfInvoiceHandler = new List<iBlufyInvoiceEngine>();
        setOFClassSessionIds = new Set<String>();
        setInvoice(sub);    
        
        for(Subscription_Line_Item__c objLineItem : sub.Subscription_Line_Items__r){
            if(objLineItem.Enrollment__r.Class_Session__c != null){
             	setOFClassSessionIds.add(objLineItem.Enrollment__r.Class_Session__c);   
            }           
            listOfInvoiceHandler.add(getHandler(sub.Payment_Frequency__c,objLineItem));
        } 
    }
    
    private IBlufyInvoiceEngine getHandler(String frequency, Subscription_Line_Item__c objLineItem){
        System.debug('frequency '+frequency);
        IBlufyInvoiceEngine handler;
        if(frequency == 'Term'){
            handler = new TermFullInvoiceHandler(objLineItem);
        }else if(frequency == 'Monthly'){
            handler = new MonthlyFullInvoiceHandler(objLineItem);
        }
        return handler;
    }
    
    public Invoice__c getInvoice(){
        return this.objInv;
    }
    
    /*
     * return sessions related to class and time limit
    *  timeLimit e.g. Next_Month, THIS_Month
    */
    public static Map<String,List<Session__c>> getClassSessions(Set<String> classIds){
        Map<String,List<Session__c>> classSessionsMap = new Map<String,List<Session__c>>();
        if(classIds.size() > 0){
            String ids = '';
             for(String cId : classIds){                
                ids += '\''+string.escapeSingleQuotes(cId)+ '\',';
            }
            ids = ids.removeEnd(',');            
            String query = 'SELECT Id, Session_Date__c, Class__c, Class_Session__c FROM Session__c WHERE Session_Date__c = THIS_MONTH AND Class_Session__c IN('+ids+')  WITH SECURITY_ENFORCED';
            for(SObject sObj : InvoiceService.getExecutedQueryRecords(query)){
                Session__c objSession = (Session__c)sObj;
                List<Session__c> sessionsList = classSessionsMap.containsKey(objSession.Class_Session__c) ? classSessionsMap.get(objSession.Class_Session__c) : 
                new List<Session__c>();
                sessionsList.add(objSession);
                classSessionsMap.put(objSession.Class_Session__c,sessionsList);            
            }
            return classSessionsMap;
        }
        return null;
    }
    
    
    /*
     * return class term map
    */
    
    public static Map<String,List<Class_Term__c>> getClassTermMap(Set<String> setOfClassIDs){
        System.debug('@@@setOfClassIDs'+setOfClassIDs);
        Map<String,List<Class_Term__c>> mapOfclassTerm = new Map<String,List<Class_Term__c>>();
        for(Class_Term__c objTerm : ClassTermService.getByClassIds(setOfClassIDs)){
            List<Class_Term__c> listOfTerm = mapOfClassTerm.containsKey(objTerm.Class__c) ? mapOfClassTerm.get(objTerm.Class__c) :
            new List<Class_Term__c>();
            listOfTerm.add(objTerm);
            mapOfClassTerm.put(objTerm.Class__c,listOfTerm);
        }
        return mapOfClassTerm;
    }
    
    //Util common methods
    public void setInvoice(Subscription__c sub){
        Blufy_Config__mdt blufyConfig = NewEnrollmentFormCntrl.getBlufyConfigDetails();  
        this.objInv = UtilityClass.fillInvoice(sub.Customer__c, sub.Location__c,sub.Id,'Recurring','Due');
        this.objInv.Invoice_Date__c = executionDate;//System.today();
        //this.objInv.Due_Date__c = executionDate;//System.today();
        if(blufyConfig.Invoice_Due_Days__c > 0){
             this.objInv.Due_Date__c = System.today().addDays(Integer.valueOf(blufyConfig.Invoice_Due_Days__c));
        }else{
            this.objInv.Due_Date__c = executionDate;
        }
    }
    
    public static Invoice_Line_Item__c createInvLineItem(Subscription_Line_Item__c objLineItem,String type,Decimal amount,String invId){
        Blufy_Config__mdt blufyConfig = NewEnrollmentFormCntrl.getBlufyConfigDetails();                              
        Invoice_Line_Item__c objInvoiceItem = UtilityClass.fillInvLineItem(invId, objLineItem.Enrollment__c, objLineItem.id, 
                                                                          objLineItem.Fee__c, null,type, amount, blufyConfig.GST_VAT_Applicable__c, blufyConfig.GST_VAT_Rate__c);
        return objInvoiceItem;
    }
    
    public static Subscription_Line_Item__c resetClassTermAndBillDate(Subscription_Line_Item__c objLineItem){
        objLineItem.put('Class_Term__c',NULL);
        objLineItem.put('Next_Bill_Date__c',NULL);
        return objLineItem;
    }
}