force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <isActive>false</isActive>
                <label>Abandoned</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
                <isActive>false</isActive>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CancelEnrolmentControllerTest.cls
@isTest
public class CancelEnrolmentControllerTest {
    	
    @testSetup
    static void testDataSetup(){
        BlufyTestUtil.init();        
    }
    
    @isTest
    static void validateCancelEnrolmentControllerrMethod1(){
        List<Account> accList = [SELECT Id, Name FROM Account WHERE Lastname = 'Gates' AND personEmail = 'test1@gmail.com'];
        List<Enrollment__c> lstOfEnrollment = [SELECT Id, Name,Status__c FROM Enrollment__c];
        CancelEnrolmentController.getEnrolmentDetail(lstOfEnrollment[0].Id);
        CancelEnrolmentController.getEnrolmentLastSessionDate(lstOfEnrollment[0].Id, Date.today().addDays(-4));
        CancelEnrolmentController.cancelEnrolmentProcess(lstOfEnrollment[0].Id,Date.today().addDays(-4),'',accList[0].Id,Date.today().addDays(-1),'');
    }
}