force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Date__c</fullName>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollments (Parent)</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <isActive>false</isActive>
                <label>Abandoned</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
                <isActive>false</isActive>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripeACHVerificationBatch.cls
global class StripeACHVerificationBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Set<Id> setParentIds;
    global Id enrollmentId;
    public StripeACHVerificationBatch(Id enrollmentId) {
        this.setParentIds = new Set<Id>();
        this.enrollmentId = enrollmentId;
    }


    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('JM :: StripeACHVerificationBatch start method called');
        Date enrollmentDate = System.today().addDays(-2);
        
        return Database.getQueryLocator([SELECT Id, Parent__c FROM Enrollment__c WHERE ID =: this.enrollmentId]);
        //return Database.getQueryLocator([SELECT Id, Parent__c FROM Enrollment__c WHERE Enrollment_Date__c =: enrollmentDate AND Status__c = 'Active']);
    }
    global void execute(Database.BatchableContext BC, List<Enrollment__c> enrollmentList){
        System.debug('JM :: StripeACHVerificationBatch execute method called');
        this.setParentIds.addAll(StripeACHVerificationBatchHelper.verifyACHAccounts(enrollmentList));
    }
    global void finish(Database.BatchableContext BC){
        System.debug('JM :: StripeACHVerificationBatch finish method is called');
        System.debug('JM :: StripeACHVerificationBatch set size : '+this.setParentIds.size());
        if(this.setParentIds.size()>0)
            Database.executeBatch(new StripeCustomerPaymentBatch(this.setParentIds),50);
    }
}