force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Advance_Scheduling_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Scheduling_Period__c</fullName>
    <label>Advance Scheduling Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Duration_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_Minutes__c</fullName>
    <label>Duration in Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Exclude_Public_Holidays__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Public_Holidays__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Holidays</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Sub Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Center where this class will be held.</inlineHelpText>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes (Location)</relationshipLabel>
    <relationshipName>Location_classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Scheduled_Till__c.field-meta.xml
<CustomField>
    <fullName>Scheduled_Till__c</fullName>
    <description>This field is used to identify the date, till session records created.</description>
    <label>Scheduled Till</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Sessions__c.field-meta.xml
<CustomField>
    <fullName>Sessions__c</fullName>
    <inlineHelpText>Number of Session used to define one Term (Term 1) of this class. The system will create subsequent Terms automatically using this definition (in Draft mode). You can edit subsequent terms as required.</inlineHelpText>
    <label>Number of Sessions</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start Date of the class.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Start Time of this class on the days selected in &apos;Days of Week&apos;.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Minutes__c</fullName>
    <label>Duration In Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollments (Location)</relationshipLabel>
    <relationshipName>Enrollments3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions (Location)</relationshipLabel>
    <relationshipName>Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time of the Session.</description>
    <inlineHelpText>Start Time of the Session. The End Time of the Session will be updated based on Duration Unit and Duration.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hours__c/Teacher_Working_Hours__c.object-meta.xml
<CustomObject>
    <description>This object is use for get and identify the working hours of teachers</description>
    <label>Teacher Working Hours</label>
    <nameField>
        <displayFormat>TWH -{000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Working Hours</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Working_Hours__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teacher Working Hours (Location)</relationshipLabel>
    <relationshipName>Teacher_Working_Hours1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Teacher_Working_Hours__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>This field is use for to store the start working  time of teacher</description>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Term</fullName>
    </customValue>
    <customValue>
        <fullName>One_Time</fullName>
        <label>One-Time</label>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
        <isActive>false</isActive>
        <label>Bi-Weekly</label>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
        <isActive>false</isActive>
        <label>One-Time</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Weekdays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mon</fullName>
    </customValue>
    <customValue>
        <fullName>Tue</fullName>
    </customValue>
    <customValue>
        <fullName>Wed</fullName>
    </customValue>
    <customValue>
        <fullName>Thu</fullName>
    </customValue>
    <customValue>
        <fullName>Fri</fullName>
    </customValue>
    <customValue>
        <fullName>Sat</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <masterLabel>Weekdays</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateSessionMonthlyBatch.cls
/*
* Name: CreateSessionMonthlyBatch
* Author : Rajesh Sahu
* created on : 20/11/2020
*
*
* Description : This Batch Class is used to create monthly session records for monthly Open classes
*/

global with sharing class CreateSessionMonthlyBatch implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext bc){
        //**************Retrieving Class with Open Status, Monthly Frequency,Advance Scheduling Unit is Month(s)  & Next Schedule Date is 
        //Today along with related Sessions,Class Session,Enrollment Records***************************
        String query = 'SELECT Id,Name,Start_Date__c,Advance_Scheduling_Period__c,Location__c, Scheduled_Till__c, ';
        query += ' Start_Time__c,Days_of_Week__c,Sessions__c,Exclude_Public_Holidays__c,Frequency__c, ';
        query += ' (SELECT Id,Duration_in_Minutes__c,Day_of_Week__c,Start_Time__c,Teacher__c,Room__c FROM Class_Sessions__r ORDER BY Start_Time__c), ';
        query += ' (SELECT Id,Enrollment_End_Date__c,Student__c,Type__c,Class_Session__c FROM Enrollments__r), ';
        query += ' (SELECT Id,Sequence__c FROM Sessions__r ORDER BY Sequence__c DESC LIMIT 1) ';
        query += ' FROM Class__c WHERE Status__c =\'Open\' AND Frequency__c = \'Monthly\'';
        query += ' WITH SECURITY_ENFORCED';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext bc, List<Class__c> clsList){
        try{
            List<Session__c> listSessionToInsert = new List<Session__c>();
            List<Student_Session__c> listStudentSession = new List<Student_Session__c>();
            List<Class__c> listClassToUpdate = new List<Class__c>();
            
            Set<String> setTeacherId   = new Set<String>();
            Set<String> setRoomId  = new Set<String>();
            
            List<Holiday__c> listOfHolidays = new List<Holiday__c>(); 
            Map<String,List<Teacher_Working_Hours__c>> mapTeacherIdToTechrWrkHour = new Map<String,List<Teacher_Working_Hours__c>>();
            Map<String,List<Teacher_Leave__c>> mapTeacherIdToTeacherLeave = new Map<String,List<Teacher_Leave__c>>();
            Map<String,List<Session__c>> mapTeacherIdToTeacherSessions = new Map<String,List<Session__c>>();
            Map<String,List<Session__c>> mapRoomIdToRoomSessions = new Map<String,List<Session__c>>();
            
            
            for(Class__c classRec : clsList){
                //*********************Retrieving Class Session related to class which specify the number of sessions per day of a Class*******************
                if(classRec.Class_Sessions__r.size() > 0){
                    for(Class_Session__c clsSess : classRec.Class_Sessions__r){
                        
                        if(String.isNotBlank(clsSess.Teacher__c))
                            setTeacherId.add(clsSess.Teacher__c);
                        if(String.isNotBlank(clsSess.Room__c))
                            setRoomId.add(clsSess.Room__c);
                    }
                }
            }
            
            //************************Retrieving Teacher Leaves,Teacher Working Hour & Holiday of specified teacher of class*******************************
            if(setTeacherId.size() > 0){
                mapTeacherIdToTeacherLeave = UtilityClass.getTeacherLeaves(setTeacherId);
                mapTeacherIdToTechrWrkHour = UtilityClass.getTeacherWorkingHour(setTeacherId);
                mapTeacherIdToTeacherSessions = UtilityClass.getTeacherRelatedSessions(setTeacherId);
                listOfHolidays = UtilityClass.getHolidays();
            }
            
            if(setRoomId.size() > 0)
                mapRoomIdToRoomSessions = UtilityClass.getRoomRelatedSessions(setRoomId);
            
            for(Class__c cls : clsList){
                Date sDate = cls.Scheduled_Till__c.addDays(1);
                DateTime strtDateTm = DateTime.newInstance(sDate.year(),sDate.month(),sDate.day(),00,00,00);
                
                Integer numberOfDays = Date.daysInMonth(sDate.year(), sDate.month());
                Date eDate = Date.newInstance(sDate.year(), sDate.month(), numberOfDays);                
                DateTime endDateTm = DateTime.newInstance(eDate.year(),eDate.month(),eDate.day(),00,00,00);
                
                Integer seq = 0;
                List<Session__c> listSession = UtilityClass.createSessions(cls,strtDateTm,endDateTm,seq,null,
                                                                           cls.Class_Sessions__r,
                                                                           null);
                if(listSession.size() > 0){
                    //*********Get Updated Sessions Based on Holiday,Teacher Leaves,Teacher Working Hour*****************
                    listSession = UtilityClass.getUpdatedSessions(seq,cls.Exclude_Public_Holidays__c,
                                                                  listSession,mapTeacherIdToTeacherLeave, mapTeacherIdToTechrWrkHour,
                                                                  listOfHolidays,mapTeacherIdToTeacherSessions,
                                                                  mapRoomIdToRoomSessions);
                }
                //mapClassIdToSessions.put(cls.Id,listSession);
                listSessionToInsert.addAll(listSession); 
                
                Class__c clsTemp = new Class__c(Id=cls.Id);
                clsTemp.put('Scheduled_Till__c',eDate);
                listClassToUpdate.add(clsTemp);
            } 
            
            if(listSessionToInsert.size() > 0){
                listSessionToInsert = SessionService.insertSessionRecords(listSessionToInsert);
                
                Map<String,List<Session__c>> mapClassIdToSessions = new Map<String,List<Session__c>>();
                for(Session__c sess : listSessionToInsert){
                    List<Session__c> listSession = new List<Session__c>();
                    String key = sess.Class__c+';'+sess.Class_Session__c;
                    if(mapClassIdToSessions.containsKey(key))
                        listSession = mapClassIdToSessions.get(key);
                    listSession.add(sess);
                    mapClassIdToSessions.put(key,listSession);
                }
                
                for(Class__c cls: clsList){
                    //*********************Retrieving Enrollments related to class*******************
                    for(Enrollment__c enrol : cls.Enrollments__r){
                        //******************Creating Student Session Records for each Enrollment based on session records*********** 
                        if(mapClassIdToSessions.get(cls.Id+';'+enrol.Class_Session__c) != null){
                            for(Session__c sess : mapClassIdToSessions.get(cls.Id+';'+enrol.Class_Session__c)){
                                Student_Session__c stuSess = UtilityClass.createStudentSessions(enrol, sess);
                                listStudentSession.add(stuSess);
                            }
                        }
                    }
                }
                System.debug('listClassToUpdate->'+listClassToUpdate);
                if(listStudentSession.size() > 0)
                    StudentSessionService.insertStudentSessionRecords(listStudentSession);
                
                ClassService.updateClassRecords(listClassToUpdate);
            }
        } catch(Exception e){
            System.debug('Line Number-->'+e.getLineNumber());
            
            Blufy_Error_Log__c blufyErrLg = new Blufy_Error_Log__c();
            blufyErrLg.put('Process_Name__c','SessionRecordsCreationBatchApex');
            blufyErrLg.put('Description__c',e.getMessage());
            blufyErrLg.put('Title__c','Session Creation Batch');
            BlufyErrorLogService.insertBlufyErrorLogRecords(new List<Blufy_Error_Log__c>{blufyErrLg});
        }
    }
    
    global void finish(Database.BatchableContext bc){
        // execute any post-processing operations
    }
}