force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Advance_Billing__c.field-meta.xml
<CustomField>
    <fullName>Advance_Billing__c</fullName>
    <label>Advance Billing Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Advance_Billing_Unit__c.field-meta.xml
<CustomField>
    <fullName>Advance_Billing_Unit__c</fullName>
    <label>Advance Billing Unit</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day(s)</fullName>
            </value>
            <value>
                <fullName>Week(s)</fullName>
            </value>
            <value>
                <fullName>Month(s)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Sessions__c.field-meta.xml
<CustomField>
    <fullName>Sessions__c</fullName>
    <inlineHelpText>Number of Session used to define one Term (Term 1) of this class. The system will create subsequent Terms automatically using this definition (in Draft mode). You can edit subsequent terms as required.</inlineHelpText>
    <label>Number of Sessions</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Start Date of the class.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Class_Term__c/Class_Term__c.object-meta.xml
<CustomObject>
    <label>Class Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Term__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Terms</relationshipLabel>
    <relationshipName>Class_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ClassTermService.cls
public class ClassTermService {
    
    public static List<Class_Term__c> getByClassIds(Set<String> setClassId){
        if(!setClassId.isEmpty()){
            try{
                List<Class_Term__c> listClassTerm = [SELECT Sessions__c, Sequence__c,Start_Date__c,Class__c,
                                                     Class__r.Advance_Billing__c,Class__r.Advance_Billing_Unit__c 
                                                     FROM Class_Term__c WHERE Class__c IN: setClassId WITH SECURITY_ENFORCED 
                                                     ORDER By Start_Date__c];
                return listClassTerm;
            }catch(System.QueryException e){
                System.debug(e.getMessage());
            }        
        }
        return new List<Class_Term__c>();
    }
    
    //Insertion of Class Term Records
    public static List<Class_Term__c> insertClassTermRecords(List<Class_Term__c> listClassTerm){
        try{
            if(listClassTerm.size() > 0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, listClassTerm,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Class Term Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    insert securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        }
        catch(Exception e){
            System.debug('Error Message-->'+e.getMessage());
        }
        return null;
    }
    
    //Updation of Class Term Records
    public static List<Class_Term__c> updateClassTermRecords(List<Class_Term__c> listClassTerm){
        try{
            if(listClassTerm.size() > 0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPDATABLE, listClassTerm,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Class Term  Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    update securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        }
        catch(Exception e){
            System.debug('Class Term Error Message-->'+e.getMessage());
        }
        return null;
    }
}