force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <inlineHelpText>Links class to a course.</inlineHelpText>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Enrollments__c.field-meta.xml
<CustomField>
    <fullName>Enrollments__c</fullName>
    <label>Enrollments</label>
    <summaryForeignKey>Enrollment__c.Class__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CourseTriggerHelper.cls
public class CourseTriggerHelper {

    public static void checkEnrollmentBeforeCourseDeletion(List<Course__c> listCourse){
        Set<String> setCourseId = new Set<String>();
        Set<String> setCourseIdContainingEnrollment = new Set<String>();
        
        for(Course__c course : listCourse){
            setCourseId.add(course.Id);
        }
        
        if(setCourseId.size() > 0){
            List<Class__c> listClassWithEnrollment = ClassService.getClassAlongContainEnrollmentByCourseId(setCourseId);
            if(listClassWithEnrollment != NULL && listClassWithEnrollment.size() > 0){
                for(Class__c cls : listClassWithEnrollment){
                    if(cls.Enrollments__r.size() > 0)
                        setCourseIdContainingEnrollment.add(cls.Course__c);
                }
            }
        }
        
        if(setCourseIdContainingEnrollment.size() > 0){
            for(Course__c course : listCourse){
                if(setCourseIdContainingEnrollment.contains(course.Id))
                    course.addError('You can not delete a course having associated enrollment(s)');
            }
        }
    }
}