force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Unchecked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentAccountTriggerHelper.cls
public class PaymentAccountTriggerHelper {
    public PaymentAccountTriggerHelper() {

    }
    public static void afterInsert(){
        System.debug('JM :: PaymentAccountTriggerHelper :: afterInsert method called');
        System.debug('JM :: '+Trigger.new.size());
        Map<Id, Id> mapAccIdPaymentAccs = new Map<Id, Id>();
        List<Payment_Account__c> lstOldPaymentAccounts = new List<Payment_Account__c>();
        // List<Payment_Account__c> lstNewPaymentAccountsCards = new List<Payment_Account__c>();
        for(Payment_Account__c obj : (List<Payment_Account__c>)Trigger.new){
            if((obj.Verification_Status__c == '' || obj.Verification_Status__c == 'Verified' || String.isBlank(obj.Verification_Status__c) == true) && obj.Active__c == true){
                System.debug('JM :: inside 2nd if : values : AccountId : '+obj.Account__c + ' : PaymentAccount Id : '+obj.Id);
                mapAccIdPaymentAccs.put(obj.Account__c, obj.Id);
            }
        }
        for(Payment_Account__c obj : [SELECT ID, Active__c 
                                        FROM Payment_Account__c
                                        WHERE Account__c IN :mapAccIdPaymentAccs.keySet() AND 
                                            ID NOT IN :mapAccIdPaymentAccs.values() AND 
                                            Active__c = true]){
                                                obj.Active__c = false;
                                                lstOldPaymentAccounts.add(obj);
                                            }
        System.debug('JM :: lstOldPaymentAccounts size :: '+lstOldPaymentAccounts.size());
        if(lstOldPaymentAccounts.size()>0){
            Update lstOldPaymentAccounts;
        }
    }
}