force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>IGCSE</fullName>
            </value>
            <value>
                <fullName>Bachelor&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Master&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Doctorate</fullName>
            </value>
            <value>
                <fullName>Short Professional Course</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Fee__c/Course_Fee__c.object-meta.xml
<CustomObject>
    <label>Course Fee</label>
    <nameField>
        <displayFormat>CF-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Course Fee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Fee__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Fee</relationshipLabel>
    <relationshipName>Course_Fee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Fee__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Fee__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Primary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Course Fee</relationshipLabel>
    <relationshipName>Course_Fee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Schedule__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applies GST if checked.</description>
    <inlineHelpText>Applies GST if checked.</inlineHelpText>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, it allows the user to remove the Fee at enrollment.</inlineHelpText>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Prorate__c.field-meta.xml
<CustomField>
    <fullName>Prorate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Applicable only for tuition fee.</inlineHelpText>
    <label>Prorate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Fee will be applied (checked) by default at the time of enrollment. The Override field can used used to allow user to remove (uncheck) the Fee.</description>
    <inlineHelpText>The Fee will be applied (checked) by default at the time of enrollment. The Override field can used used to allow the user to remove (uncheck) the Fee.</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price Per Session.</description>
    <inlineHelpText>Price Per Session.</inlineHelpText>
    <label>Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Number of Units</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Term</fullName>
    </customValue>
    <customValue>
        <fullName>One_Time</fullName>
        <label>One-Time</label>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
        <isActive>false</isActive>
        <label>Bi-Weekly</label>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
        <isActive>false</isActive>
        <label>One-Time</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseFeeService.cls
public class CourseFeeService{
    
    public static List<Course_Fee__c> getByCourseId(String sId){  
        try{
            List<Course_Fee__c> listCourseFee = new List<Course_Fee__c>();
            for(Course_Fee__c crFee: [SELECT Id, Name, Fee__c, Fee__r.Name, Fee__r.Amount__c, Fee__r.Unit_Price__c, Course__c,
                                      Fee__r.Schedule__c, Fee__r.Units__c, Fee__r.Type__c, Fee__r.Frequency__c, 
                                      Fee__r.Required__c, Fee__r.Override__c,Fee__r.GST_Applicable__c,                                       
                                      Fee__r.Prorate__c                                     
                                      FROM Course_Fee__c 
                                      WHERE Course__c =: sId AND Fee__r.Amount__c != null AND Fee__r.Type__c != null 
                                      AND Fee__r.RecordTypeId=:ConstantClass.primaryFeeRecordTypeId WITH SECURITY_ENFORCED]){
                                          listCourseFee.add(crFee);
                                      }
            return listCourseFee;  
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null;    
    }

    public static List<Course_Fee__c> getByCourseIdOrType(String sId, String type, String frequency){        
        try{
            List<Course_Fee__c> listCourseFee = new List<Course_Fee__c>();        
            for(Course_Fee__c crFee: [SELECT Id, Name, Fee__c, Fee__r.Name, Fee__r.Amount__c, Fee__r.Unit_Price__c, Course__c,
                                             Fee__r.Schedule__c, Fee__r.Units__c, Fee__r.Type__c, Fee__r.Frequency__c, 
                                             Fee__r.Required__c, Fee__r.Override__c,Fee__r.GST_Applicable__c
                                      FROM Course_Fee__c 
                                      WHERE Course__c =: sId AND Fee__r.Amount__c != null AND Fee__r.Type__c =:type  
                                      AND Fee__r.RecordTypeId=:ConstantClass.primaryFeeRecordTypeId
                                      WITH SECURITY_ENFORCED]){
                                        listCourseFee.add(crFee);
            }
            return listCourseFee;
        }    
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null;      
    }
}