force-app/main/default/objects/Account/recordTypes/Location.recordType-meta.xml
<RecordType>
    <fullName>Location</fullName>
    <active>true</active>
    <description>Select this option to create a new school location or center</description>
    <label>Location</label>
</RecordType>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Advance_Scheduling_Period__c.field-meta.xml
<CustomField>
    <fullName>Advance_Scheduling_Period__c</fullName>
    <label>Advance Scheduling Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <default>true</default>
                <label>1</label>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
            <value>
                <fullName>9</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Advance_Scheduling_Unit__c.field-meta.xml
<CustomField>
    <fullName>Advance_Scheduling_Unit__c</fullName>
    <label>Advance Scheduling Unit</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Frequency__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Day(s)</fullName>
            </value>
            <value>
                <fullName>Week(s)</fullName>
            </value>
            <value>
                <fullName>Month(s)</fullName>
            </value>
            <value>
                <fullName>Term(s)</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Auto_Schedule__c.field-meta.xml
<CustomField>
    <fullName>Auto_Schedule__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Auto Schedule</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <inlineHelpText>Links class to a course.</inlineHelpText>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>End Date of the class. End Date will be automatically updated when the sessions for this class are scheduled.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Start Time of this class on the days selected in &apos;Days of Week&apos;.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/recordTypes/Course.recordType-meta.xml
<RecordType>
    <fullName>Course</fullName>
    <active>true</active>
    <label>Course</label>
</RecordType>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Not using this</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class associated with this Session.</description>
    <inlineHelpText>Class associated with this Session.</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time of the Session.</description>
    <inlineHelpText>Start Time of the Session. The End Time of the Session will be updated based on Duration Unit and Duration.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Weekdays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mon</fullName>
    </customValue>
    <customValue>
        <fullName>Tue</fullName>
    </customValue>
    <customValue>
        <fullName>Wed</fullName>
    </customValue>
    <customValue>
        <fullName>Thu</fullName>
    </customValue>
    <customValue>
        <fullName>Fri</fullName>
    </customValue>
    <customValue>
        <fullName>Sat</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <masterLabel>Weekdays</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CourseTriggerTest.cls
@isTest
public class CourseTriggerTest {
	
    static testmethod void test1(){
        try{
            
            Account parentObj = BlufyTestUtil.createParentRec('Gates','test1@gmail.com');
            insert parentObj;
            system.debug('parentObj ->'+parentObj);
            
            Account studentObj = BlufyTestUtil.createStudentRec('Thomas','test1@gmail.com');
            insert studentObj;
            
            Course__c course  		  = BlufyTestUtil.createCourseRec('Test', 'Active', 'Test');
            insert course;        
            
            Account location      	  = BlufyTestUtil.createLocationRec('Test');
            insert location;
            
            Account tch      		  = BlufyTestUtil.createTeacherRec('Test', location.Id);
            insert tch;
            
            //create class and update
            Class__c cls   			  = BlufyTestUtil.createClassRec('Test', Course.Id, ConstantClass.classType, 
                                                                     ConstantClass.draftStatus, tch.Id, 40, 
                                                                     ConstantClass.fixedType, 21, Date.today()+1,
                                                                     Time.newInstance(4,4,5,6),
                                                                     ConstantClass.oneTimeFrequency, null);
            cls.Advance_Scheduling_Period__c = '2';
            cls.End_Date__c = System.today().addMonths(6);
            cls.Advance_Scheduling_Unit__c = '';
            cls.Auto_Schedule__c = true;
            insert cls;
            
            Class__c cls1   			  = BlufyTestUtil.createClassRec('Test', Course.Id, ConstantClass.classType, 
                                                                         ConstantClass.draftStatus, tch.Id, 40, 
                                                                         ConstantClass.ongoingClsType, 21, Date.today()+1,
                                                                         Time.newInstance(4,4,5,6),
                                                                         ConstantClass.monthlyFrequency, null);
            cls1.Advance_Scheduling_Period__c = '2';
            cls1.End_Date__c = System.today().addMonths(6);
            cls1.Advance_Scheduling_Unit__c = '';
            cls1.Auto_Schedule__c = true;
            insert cls1;
            
            Class_Session__c clsSess = BlufyTestUtil.createClassSessionRec(cls.Id,Time.newInstance(10,30,00,00),'120');
            clsSess.Teacher__c = tch.Id;
            clsSess.Start_Time__c = Time.newInstance(10, 00, 00, 00);
            clsSess.Day_of_Week__c = 'Mon';
            insert clsSess;
            
            Class_Session__c clsSess1 = BlufyTestUtil.createClassSessionRec(cls.Id,Time.newInstance(10,30,00,00),'120');
            clsSess1.Teacher__c = tch.Id;
            clsSess1.Start_Time__c = Time.newInstance(10, 00, 00, 00);
            clsSess1.Day_of_Week__c = 'Wed';
            insert clsSess1;
            
            Class_Session__c clsSess2 = BlufyTestUtil.createClassSessionRec(cls1.Id,Time.newInstance(10,30,00,00),'120');
            clsSess2.Teacher__c = tch.Id;
            clsSess2.Start_Time__c = Time.newInstance(12, 00, 00, 00);
            clsSess2.Day_of_Week__c = 'Tue';
            insert clsSess2;
            
            Session__c sessionObj = BlufyTestUtil.createSessionRec(location.Id,tch.Id, cls.Id, Date.today().addDays(7), Time.newInstance(10, 00, 00, 00), 'Scheduled', '', '60','Standard',null);
            sessionObj.Class_Session__c = clsSess.Id;
            insert sessionObj;
            
            Enrollment__c enrollObj = BlufyTestUtil.createEnrollment(cls.Id, Date.today().addDays(-4), location.Id, studentObj.Id, ConstantClass.enrolledStatus, true,  Date.today().addDays(-4),parentObj.id);
            insert enrollObj;
            
            delete course;
            Test.startTest();
            Class__c clssObj = [SELECT Id,Advance_Scheduling_Period__c FROM Class__c WHERE Id =: cls.Id];
            System.assertEquals('2',clssObj.Advance_Scheduling_Period__c);  
            Test.stopTest();
        }
        catch(exception e){
            
        }
    }
}