force-app/main/default/objects/Blufy_Config__mdt/Blufy_Config__mdt.object-meta.xml
<CustomObject>
    <label>Blufy Config</label>
    <pluralLabel>Blufy Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Blufy_Config__mdt/fields/GST_VAT_Applicable__c.field-meta.xml
<CustomField>
    <fullName>GST_VAT_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GST/VAT Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/GST_VAT_Rate__c.field-meta.xml
<CustomField>
    <fullName>GST_VAT_Rate__c</fullName>
    <defaultValue>0</defaultValue>
    <label>GST/VAT Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Invoice_Due_Days__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Due_Days__c</fullName>
    <label>Invoice Due Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Monthly_Invoice_Cycle__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Invoice_Cycle__c</fullName>
    <label>Monthly Invoice Cycle</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Last_Month</fullName>
            </value>
            <value>
                <fullName>Next_Month</fullName>
                <default>true</default>
                <label>Next_Month</label>
            </value>
            <value>
                <fullName>This_Month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Segment_Type__c.field-meta.xml
<CustomField>
    <fullName>Segment_Type__c</fullName>
    <label>Segment Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Enrichment</fullName>
                <default>true</default>
                <label>Enrichment</label>
            </value>
            <value>
                <fullName>Professional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Terms_and_Conditions_Description__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions_Description__c</fullName>
    <label>Terms and Conditions Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Blufy_Config__mdt/fields/Terms_and_Conditions_Title__c.field-meta.xml
<CustomField>
    <fullName>Terms_and_Conditions_Title__c</fullName>
    <label>Terms and Conditions Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BlufyConfigService.cls
public class BlufyConfigService {
    
    public static List<Blufy_Config__mdt> getByDeveloperName(String developerName){
        if(String.isNotBlank(developerName)){
            try {
                List<Blufy_Config__mdt> listBlufyConfig = [SELECT Monthly_Invoice_Cycle__c,Terms_and_Conditions_Description__c,
                                                           Terms_and_Conditions_Title__c,GST_VAT_Applicable__c,GST_VAT_Rate__c,
                                                           Invoice_Due_Days__c,Logo__c,Segment_Type__c
                                                           FROM Blufy_Config__mdt 
                                                           WHERE DeveloperName =: developerName 
                                                           WITH SECURITY_ENFORCED];
                return listBlufyConfig;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    
}