force-app/main/default/objects/Blufy_Config__mdt/Blufy_Config__mdt.object-meta.xml
<CustomObject>
    <label>Blufy Config</label>
    <pluralLabel>Blufy Config</pluralLabel>
</CustomObject>

force-app/main/default/objects/Blufy_Config__mdt/fields/Logo__c.field-meta.xml
<CustomField>
    <fullName>Logo__c</fullName>
    <label>Logo</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Total_Paid_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Amount__c</fullName>
    <label>Total Paid Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer invoice line items(child records of invoice)</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/GST_Amount__c.field-meta.xml
<CustomField>
    <fullName>GST_Amount__c</fullName>
    <label>GST Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>to store related invoice details</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/InvoiceDetailController.cls
Public with sharing class InvoiceDetailController{
    public Invoice__c invoice{get;set;}
    public List<Payment__c> listPayment{get;set;}
    public String logo{get;set;}
	    
    public InvoiceDetailController(){
        invoice = new Invoice__c();
        listPayment = new List<Payment__c>();
        string invId = Apexpages.currentPage().getParameters().get('Id');
        
        List<Invoice__c> invList = InvoiceService.getInvoiceById(invId);  
        if(invList.size()>0){
            if(invList[0].Total_Paid_Amount__c == NULL)
                invList[0].Total_Paid_Amount__c = 0;
            
            if(invList[0].Invoice_Line_Items__r.size() > 0){
                for(Invoice_Line_Item__c invItm : invList[0].Invoice_Line_Items__r){
                    if(invItm.GST_Amount__c == NULL)
                        invItm.GST_Amount__c = 0;
                }
            }
            invoice = invList[0];
            if(invoice.Payments__r.size() > 0){
                listPayment = invoice.Payments__r;
            }
            
            List<Blufy_Config__mdt> listBlufyConfig = BlufyConfigService.getByDeveloperName('Default');
            if(listBlufyConfig.size() > 0){
                logo = listBlufyConfig[0].Logo__c;
            }
        }       
    }
}