force-app/main/default/objects/Account/fields/Customer_key__c.field-meta.xml
<CustomField>
    <fullName>Customer_key__c</fullName>
    <label>Customer key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Is_Verified__c.field-meta.xml
<CustomField>
    <fullName>Is_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the type of Payment</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Unchecked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripeAccountVerifyBatch.cls
/*
Name        :       StripeAccountVerifyBatch
Date        :       7th Dec 2020 
Description :       StripeAccountVerifyBatch is used to have all the Payment Account records of ACH type to verify the Status and Activate them.
Developer   :       TMC
*/
global without sharing class StripeAccountVerifyBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('JM :: StripeAccountVerifyBatch start method called');
        //Date pastDate = System.today().addDays(-2);
        Date pastDate = System.today();//For Testing purpose only
        System.debug(Database.query('SELECT Id, Verification_Status__c,Account__c, Account__r.Customer_key__c, Active__c, Stripe_Token__c, Is_Verified__c,Type__c,Stripe_ID__c '+
                                                'FROM Payment_Account__c '+
                                                'WHERE CreatedDate <= :pastDate AND '+ 
                                                //'Is_Verified__c = FALSE AND '+
                                                '(Verification_Status__c != \'Pass\' OR Verification_Status__c != \'New\') AND ' +
                                                'Account__r.Customer_key__c != NULL AND '+ 
                                                'Stripe_Token__c != NULL AND '+
                                                'Stripe_ID__c != NULL AND ' + 
                                                'Type__c = \'ACH\' WITH SECURITY_ENFORCED'
                                            ));
        return Database.getQueryLocator('SELECT Id, Verification_Status__c, Account__c, Account__r.Customer_key__c, Stripe_Token__c,Active__c, Is_Verified__c,Type__c,Stripe_ID__c '+
                                          'FROM Payment_Account__c '+
                                          'WHERE CreatedDate >= :pastDate AND '+ 
                                           //'Is_Verified__c = FALSE AND '+
                                           '(Verification_Status__c != \'Pass\' OR Verification_Status__c != \'New\') AND '+
                                           'Account__r.Customer_key__c != NULL AND '+ 
                                           'Stripe_Token__c != NULL AND '+
                                           'Stripe_ID__c != NULL AND ' + 
                                           'Type__c = \'ACH\' WITH SECURITY_ENFORCED'
                                        );
    }
    global void execute(Database.BatchableContext BC, List<Payment_Account__c> lstPaymentAccs){
        System.debug('JM :: StripeACHVerificationBatch execute method called');
        System.debug('JM :: lstPaymentAccs : '+lstPaymentAccs);
        StripeAccountVerifyBatchHelper.verifyACHAccounts(lstPaymentAccs);
    }
    global void finish(Database.BatchableContext BC){
        System.debug('JM :: StripeACHVerificationBatch finish method is called');
    }
}