force-app/main/default/objects/Account/fields/Customer_key__c.field-meta.xml
<CustomField>
    <fullName>Customer_key__c</fullName>
    <label>Customer key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Is_Verified__c.field-meta.xml
<CustomField>
    <fullName>Is_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the type of Payment</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Unchecked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripeAccountVerifyBatchHelper.cls
/*
Name        :       StripeAccountVerifyBatchHelper
Date        :       8th Dec 2020
Description :       StripeAccountVerifyBatchHelper will be used by StripeAccountVerifyBatch and here the Payment_Account__c records will be verified.
Developer   :       TMC
*/
public without sharing class StripeAccountVerifyBatchHelper {
    public static void verifyACHAccounts(List<Payment_Account__c> lstPaymentAccs){
        List<Payment_Account__c> paymentAccounts = new List<Payment_Account__c>();
        System.debug('JM :: verifyACHAccounts method is called');
        for(Payment_Account__c paymentAccount : lstPaymentAccs){
            //if(paymentAccount.Type__c == 'ACH' && paymentAccount.Is_Verified__c == FALSE){
                String verficationStatus = StripeUtility.getVerfiyStripeBank(paymentAccount.Account__r.Customer_key__c,paymentAccount.Stripe_ID__c);
                System.debug('FOR : ' + paymentAccount.Id + ' :: Verfication Status :: '+verficationStatus);
                
                if( String.isNotBlank(verficationStatus) && paymentAccount.Verification_Status__c != verficationStatus){
                    paymentAccount.Verification_Status__c = verficationStatus;
                    paymentAccount.Active__c = verficationStatus.compareTo('pass') == 0 || verficationStatus.compareTo('verfication') == 0 || verficationStatus.compareTo('verified') == 0 ? true : false;  
                    paymentAccounts.add(paymentAccount);
                }
            //}
        }
        System.debug('JM : paymentAccounts.size() ' + paymentAccounts.size());
        System.debug('JM : paymentAccounts values : '+ paymentAccounts);
        if(paymentAccounts.size()>0){
            PaymentAccountService.updatePaymentAccountRecords(paymentAccounts);
        }
    }
}