force-app/main/default/objects/Account/fields/Customer_key__c.field-meta.xml
<CustomField>
    <fullName>Customer_key__c</fullName>
    <label>Customer key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>Select this option to create a new account for other purposes (eg. Referrer, Individual Agent etc)</description>
    <label>Other</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Automation_Applied__c.field-meta.xml
<CustomField>
    <fullName>Automation_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>to store account details if record type is customer</description>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice (Customer)</relationshipLabel>
    <relationshipName>Invoice_Customer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>calculate from gross total and gst tax amount</description>
    <formula>Gross_Total__c  +  GST_Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments (Parent)</relationshipLabel>
    <relationshipName>Payments1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>GIRO</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transaction</fullName>
                <default>true</default>
                <label>Transaction</label>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the type of Payment</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Log__c/Payment_Log__c.object-meta.xml
<CustomObject>
    <label>Payment Log</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Payment Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Log__c/fields/API_Status__c.field-meta.xml
<CustomField>
    <fullName>API_Status__c</fullName>
    <label>API Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Charge_Id__c.field-meta.xml
<CustomField>
    <fullName>Charge_Id__c</fullName>
    <externalId>true</externalId>
    <label>Charge Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payment Logs</relationshipLabel>
    <relationshipName>Payment_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripePaymentBatchHelper.cls
/* Name         : StripePaymentBatchHelper
 * Date         : 10th Dec 2020
 * Author       : 
 * Description  : This is a helper class for StripeCustomerPaymentBatch batch class
**/
public without sharing class StripePaymentBatchHelper {
    public static void getCustomerChargeDetails(List<Invoice__c> lstInvoices){
        Set<Id> setIds = new Set<Id>();
        List<Invoice__c> lstTempInvoices = new List<Invoice__c>(); 
        for(Invoice__c obj : lstInvoices){
            setIds.add(obj.Customer__c);
            List<Payment__c> lstPayments = obj.Payments__r;
            Boolean isSuccess = false;
            for(Payment__c paymentObj : lstPayments){
                if(paymentObj.Status__c == 'Success')
                    isSuccess = true;
            }   
            if(!isSuccess)
                lstTempInvoices.add(obj);
        }
        System.debug('setIds size : '+setIds.size());
        SYstem.debug('setIds : '+setIds);
        System.debug('lstTempInvoices :: '+lstTempInvoices.size());
        System.debug('lstTempInvoices data :: '+lstTempInvoices);
        
        Map<Id, Payment_Account__c> mapAccountWithPaymentAccount = new Map<Id, Payment_Account__c>();
        for(Payment_Account__c obj : [Select Id,Account__c, Account__r.Customer_key__c, Type__c, Stripe_ID__c
                                        FROM Payment_Account__c 
                                        WHERE Account__c in : setIds AND Active__c = TRUE]){
                                            if(!mapAccountWithPaymentAccount.containsKey(obj.Account__c))
                                                mapAccountWithPaymentAccount.put(obj.Account__c, obj);
                                        }
        setIds.clear();
        System.debug('mapAccountWithPaymentAccount size : '+mapAccountWithPaymentAccount.size());
        
    
      //List<CustomClass> lstCustomClassObjs = new List<CustomClass>();
        List<Payment_Log__c> lstPaymentLogs = new List<Payment_Log__c>();
        List<Payment__c> lstPayments = new List<Payment__c>();
        Map<Id,Invoice__c> mapInvoicesUpdated = new Map<Id,Invoice__c>();
        for(Invoice__c obj : lstTempInvoices){
            if(mapAccountWithPaymentAccount.containsKey(obj.Customer__c)){
                HttpResponse resp  = StripeUtility.getStripeCharge(Integer.valueOf(obj.Total_Amount__c*100),'usd',mapAccountWithPaymentAccount.get(obj.Customer__c).Account__r.Customer_key__c,mapAccountWithPaymentAccount.get(obj.Customer__c).Stripe_ID__c);
                if(resp != null){

                    System.debug(resp.getBody());
                    String status ='none';

                    if(resp.getStatusCode()==200){
                        status = (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('status');

                        Payment_Log__c paymentLogObj = new Payment_Log__c(Charge_Id__c = (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('id'),
                                                                            Invoice__c = obj.Id, 
                                                                            API_Status__c = status.compareTo('succeeded')==0 || status.compareTo('pending')==0?'Success':'Failure', 
                                                                            Message__c = status.compareTo('pending')==0?'Payment is Pending.' : status.compareTo('failed')==0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_message') : status.compareTo('succeeded')==0 ? 'Payment is Successful.' : '',
                                                                            //Code__c will be containing the details only incase of failed
                                                                            Code__c = status.compareTo('failed')==0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_code') : '', 
                                                                            Type__c = status.compareTo('succeeded')==0 || status.compareTo('pending')==0 ? 'OK' : 'Failed' 
                                                                    );
                        System.debug('status code in 200');
                        lstPaymentLogs.add(paymentLogObj);
                        
                    }
                    else{
                        System.debug('status code is : '+resp.getStatusCode());
                        Payment_Log__c paymentLogObj = new Payment_Log__c(Invoice__c = obj.Id, 
                                                                            API_Status__c = 'Failure', 
                                                                            Message__c = (String)((Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('error')))).get('message'), 
                                                                            Code__c = String.valueOf(resp.getStatusCode()), 
                                                                            Type__c= (String)((Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('error')))).get('type')
                                                                    );
                        lstPaymentLogs.add(paymentLogObj);
                    }
                    lstPayments.add(new Payment__c(
                        Parent__c = obj.Customer__c, 
                        Invoice__c = obj.Id, 
                        Amount__c = obj.Total_Amount__c, 
                        Payment_Mode__c = mapAccountWithPaymentAccount.get(obj.Customer__c).Type__c.compareTo('Card')==0 ? 'Credit Card' : mapAccountWithPaymentAccount.get(obj.Customer__c).Type__c.compareTo('ACH') == 0 ? 'ACH' : 'Other',
                        Status__c=status.compareTo('pending')==0?'Pending':status.compareTo('succeeded')==0?'Success':'Failed',
                        Payment_Date__c=System.today(),
                        Comments__c = status.compareTo('pending')==0?'Payment is Pending.': status.compareTo('failed')==0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_code') : status.compareTo('succeeded')==0 ? 'Payment Successful.' : '',
                        Payment_Reference__c = resp.getStatusCode()==200 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('id') : 'NULL'
                        ));

                    if(status.compareTo('succeeded')==0 && mapAccountWithPaymentAccount.get(obj.Customer__c).Type__c.compareTo('Card')==0) {
                        if(mapInvoicesUpdated.containsKey(obj.Id))
                            mapInvoicesUpdated.get(obj.Id).Status__c = 'Paid';
                        else
                            mapInvoicesUpdated.put(obj.Id, new Invoice__c(Id = obj.Id, Status__c = 'Paid'));
                    }
                    if(mapInvoicesUpdated.containsKey(obj.Id))
                        mapInvoicesUpdated.get(obj.Id).Automation_Applied__c = true;
                    else
                        mapInvoicesUpdated.put(obj.Id, new Invoice__c(Id = obj.Id, Automation_Applied__c = true));

                    system.debug('lstPayments'+lstPayments);
                    
                }
                else {
                    System.debug('mapAccountWithPaymentAccount value not found : '+obj.Customer__c);
                }
            }
            else{
                System.debug('Error : Response is Null');
            }
        }
        if(lstPaymentLogs.size()>0){
            PaymentLogService.insertPaymentLogRecords(lstPaymentLogs);
        }
        
        if(lstPayments.size()>0){
            PaymentService.insertPaymentRecords(lstPayments);
        }
        if(mapInvoicesUpdated.values().size()>0){
            update mapInvoicesUpdated.values();
        }
    }
}