force-app/main/default/objects/Account/fields/Customer_key__c.field-meta.xml
<CustomField>
    <fullName>Customer_key__c</fullName>
    <label>Customer key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Is_Verified__c.field-meta.xml
<CustomField>
    <fullName>Is_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the type of Payment</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Unchecked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestStripeACHVerificationBatch.cls
@isTest
private class TestStripeACHVerificationBatch {
    @testSetup  
    static void testSetUp(){
        
      
        Account accountObj = new Account(Name='testAccount',Customer_key__c='testCutomerKey');
        Insert accountObj;
        
        Payment_Account__c  paymentAccount = new Payment_Account__c(Verification_Status__c='new',Account__c=accountObj.id ,
                                                                    Active__c= true,Stripe_Token__c='testToken',Is_Verified__c=false,
                                                                    Stripe_ID__c='testId',Type__c='ACH');
        
       
        Insert paymentAccount;
        
        
        Datetime yesterday = Datetime.now().addDays(-1);
        Test.setCreatedDate(paymentAccount.Id, DateTime.newInstance(2012,12,12));
        
        
        system.debug('created date ---->'+paymentAccount.CreatedDate);
        
    }
    
    @isTest
    static void test1(){
        test.startTest();
        Test.setMock(HttpCalloutMock.class, new StrpeUtilityMock());
        StripeACHVerificationScheduler sh1 = new StripeACHVerificationScheduler(); 
        String sch = '0 0 23 * * ?';
        system.schedule('Test StripeACHVerificationScheduler Check', sch, sh1);
        test.stopTest();
    }
    
    
}