force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_with_contact__c.field-meta.xml
<CustomField>
    <fullName>Relationship_with_contact__c</fullName>
    <label>Relationship with contact</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Relationship_With_Student__c.field-meta.xml
<CustomField>
    <fullName>Relationship_With_Student__c</fullName>
    <label>Relationship With Student</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Teacher_User__c.field-meta.xml
<CustomField>
    <fullName>Teacher_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Teachers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Parent</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollments (Parent)</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Stage__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Contacted</fullName>
            </value>
            <value>
                <fullName>Unqualified</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
                <isActive>false</isActive>
                <label>Abandoned</label>
            </value>
            <value>
                <fullName>Enrolled</fullName>
                <isActive>false</isActive>
                <label>Enrolled</label>
            </value>
            <value>
                <fullName>Terminated</fullName>
                <isActive>false</isActive>
                <label>Terminated</label>
            </value>
            <value>
                <fullName>Waitlisted</fullName>
                <isActive>false</isActive>
                <label>Waitlisted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountService.cls
public class AccountService {
    
    public static List<Account> getEnrollmentByParentIdAlongWithEnrolId(String accId,String enrolId){
        if(String.isNotBlank(accId)){
            try {
                List<Account> listAccount = [SELECT Id,(SELECT Id FROM Enrollments1__r 
                                                        WHERE Status__c =: ConstantClass.enrolledStatus
                                                        AND Id !=: enrolId)
                                             FROM Account WHERE Id =: accId WITH SECURITY_ENFORCED];
                return listAccount;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
         }
        return null;
    }
    
    public static List<Account> getCorporateOrCustomerById(String accId,Boolean isCorporateAccount){
        if(String.isNotBlank(accId)){
            try {
                List<Account> listAccount = new List<Account>();
                if(isCorporateAccount){
                    listAccount = [SELECT Id, Name, PersonEmail FROM Account WHERE Id=:accId WITH SECURITY_ENFORCED LIMIT 1];
                }
                else{
                    listAccount = [SELECT Id,Name,FirstName,LastName,PersonEmail,PersonMobilePhone,PersonMailingStreet,PersonMailingStateCode,PersonMailingCity,
                                   PersonMailingCountryCode,PersonMailingPostalCode,Relationship_with_contact__c,Gender__c,
                                   PersonBirthDate,Relationship_With_Student__c
                                   FROM Account WHERE Id=:accId WITH SECURITY_ENFORCED LIMIT 1];
                    
                }
                return listAccount;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    
    public static List<Account> getAccountByEmailId(String emailId){
        if(String.isNotBlank(emailId)){
            try {
                List<Account> listAccount = [SELECT Id, Name,PersonContactId, (SELECT Id, FirstName, LastName, PersonBirthDate FROM Students__r) 
                                   FROM Account WHERE PersonEmail =: emailId 
                                   WITH SECURITY_ENFORCED LIMIT 1];
                    return listAccount;
                }catch (System.QueryException e) {
                    System.debug(e.getMessage());
                }        
            }
            return null;
    }
    
    public static List<Account> getByTeacherRecTypeId(){
        try {
            return [SELECT Id, Name FROM Account 
                    WHERE recordtype.Id =: ConstantClass.teacherRecordTypeId
                    AND Teacher_user__c =: UserInfo.getUserId()
                    WITH SECURITY_ENFORCED];
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        } 
        return null;
    }
    
    public static List<Account> getByTeacherLocationId(Set<Id> teacherLocationIds){
        try {
            return [SELECT Id,Name FROM Account 
                    WHERE recordtype.Id =: ConstantClass.locationRecordsTypeId 
                    AND Id IN: teacherLocationIds
                    WITH SECURITY_ENFORCED];
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        } 
        return null;
    }
    
    public static List<Account> getByLocationRecTypeId(){
        try {
            return [SELECT Id,Name FROM Account 
                    WHERE recordtype.Id =: ConstantClass.locationRecordsTypeId
                    WITH SECURITY_ENFORCED];
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        } 
        return null;
    }
    
    public static List<Account> getByEnrollLocationPicklist(Set<String> locationPicklist){
        try {
            return [SELECT Id, Name FROM Account 
                    WHERE Name IN : locationPicklist
                    AND RecordType.Name =: ConstantClass.locationRecordType
                    WITH SECURITY_ENFORCED];
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        } 
        return null;
    }
    
    public static List<Account> getAccountByEmail(String email){
        List<Account> listAccount = new List<Account>();
        try {
            listAccount =  [SELECT Id FROM Account WHERE PersonEmail =: email AND RecordType.Id =: ConstantClass.customerRecTypeId
                            WITH SECURITY_ENFORCED LIMIT 1];
            
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        } 
        return listAccount;
    }
    
    //Upsertion of Account Records
    public static List<Account> upsertAccountRecords(List<Account> listAccount){
        try{
            System.debug('listAccount-->'+listAccount);
            if(listAccount.size() > 0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPSERTABLE, listAccount,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Account Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    upsert securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        }
        catch(Exception e){
            System.debug('Account Error Message--->'+e.getMessage());
        }
        return null;
    }
}