force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field have lookup of location object which we use to identify account records based on location object records</description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoCompleteCmpController.cls
public class AutoCompleteCmpController {
    @auraEnabled(cacheable=true)
    public static List<SObject> getRecords(String searchString, String objectApiName, String idFieldApiName, String valueFieldApiName, String extendedWhereClause, Integer maxRecords){
        Set<String> fieldsApiName = new Set<String>{'Id', 'Name'};
            // if(String.isNotBlank(objectApiName) && objectApiName.endsWith('__c'))
            //objectApiName = 'educato__' + objectApiName;
            //System.debug('Namespace-->'+ConstantClass.nameSpace);
            // System.debug('objectApiName@@@@@-->'+objectApiName);
            Boolean isAccessible = FieldPremissionCrudUtility.checkReadPermission(objectApiName,fieldsApiName,false);    
        if(isAccessible){
            searchString = String.escapeSingleQuotes(searchString);
            objectApiName = String.escapeSingleQuotes(objectApiName);
            idFieldApiName = String.escapeSingleQuotes(idFieldApiName);
            valueFieldApiName = String.escapeSingleQuotes(valueFieldApiName);
            
            if(extendedWhereClause == null){
                extendedWhereClause = '';
            }
            System.debug('@@@@@-->'+extendedWhereClause);
            //if(String.isNotBlank(objectApiName) && objectApiName.endsWith('__c'))
           //     objectApiName = 'educato__' + objectApiName;
            String query = 'SELECT '+idFieldApiName+', '+valueFieldApiName+' FROM '+objectApiName+' WHERE '+valueFieldApiName+' LIKE \'%'+String.escapeSingleQuotes(searchString)+'%\' '+extendedWhereClause+' WITH SECURITY_ENFORCED LIMIT '+maxRecords;
            if(objectApiName.equalsIgnoreCase('Account')){
                if(extendedWhereClause.startsWith('001'))
                    extendedWhereClause = ' AND Parent__c = \'' +extendedWhereClause+ '\' AND Recordtype.Name =\'Customer\' ';
                //query = 'SELECT '+idFieldApiName+', '+valueFieldApiName+',LastName,PersonEmail FROM '+objectApiName+' WHERE Recordtype.Name =\'Customer\' AND '+valueFieldApiName+' LIKE \'%'+searchString+'%\' '+extendedWhereClause+' LIMIT '+maxRecords;
                query = 'SELECT '+idFieldApiName+', '+valueFieldApiName+',LastName,PersonEmail FROM '+objectApiName+' WHERE '+valueFieldApiName+' LIKE \'%'+String.escapeSingleQuotes(searchString)+'%\' '+extendedWhereClause+' WITH SECURITY_ENFORCED LIMIT '+maxRecords;
            }       
            System.debug('@@@@-->'+query);
            return Database.query(query);
        }
        return null;
    }

    @AuraEnabled(cacheable = true)
    public static List<SObject> findRecords(String searchKey, String objectName, String searchField,String extendedWhereClause){
        System.debug(System.LoggingLevel.DEBUG,extendedWhereClause );
        String key = '%' + searchKey + '%';
        String QUERY = 'Select Id, '+searchField+' From '+objectName +' Where '+searchField +' LIKE :key';
        
        if(String.isNotBlank(extendedWhereClause) && (extendedWhereClause.containsIgnoreCase('Parent') || extendedWhereClause.containsIgnoreCase('Student'))){
            QUERY = 'Select Id, '+searchField+',FirstName From '+objectName +' Where '+searchField +' LIKE :key';
        }
        if(objectName.equalsIgnoreCase('Course__c')){
            QUERY = 'Select Id, '+searchField+',Location__r.Name From '+objectName +' Where '+searchField +' LIKE :key';
        }
        if(String.isNotBlank(extendedWhereClause))
            QUERY += extendedWhereClause;
        QUERY += ' WITH SECURITY_ENFORCED LIMIT 5';
        System.debug(System.LoggingLevel.DEBUG, QUERY);
        List<SObject> sObjectList = Database.query(QUERY);
        return sObjectList;
    }
}