force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field have lookup of location object which we use to identify account records based on location object records</description>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <inlineHelpText>Maximum number of students that can be enrolled. &apos;Allow Overbooking&apos; checkbox can be used to allow enrolling more than the capacity limit.</inlineHelpText>
    <label>Capacity</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Center where this class will be held.</inlineHelpText>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes (Location)</relationshipLabel>
    <relationshipName>Location_classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>A Fixed class will have a defined number of session whereas an Ongoing class can have unlimited number of sessions.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <label>Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Capacity__c.field-meta.xml
<CustomField>
    <fullName>Capacity__c</fullName>
    <label>Capacity</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Group</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Class associated with this Session.</description>
    <inlineHelpText>Class associated with this Session.</inlineHelpText>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Class_Session__c.field-meta.xml
<CustomField>
    <fullName>Class_Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Class Session</label>
    <referenceTo>Class_Session__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions (Location)</relationshipLabel>
    <relationshipName>Sessions1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Room</label>
    <referenceTo>Room__c</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <description>Date on which the Session will occur.</description>
    <inlineHelpText>Date on which the Session will occur.</inlineHelpText>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Placeholder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Weekdays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mon</fullName>
    </customValue>
    <customValue>
        <fullName>Tue</fullName>
    </customValue>
    <customValue>
        <fullName>Wed</fullName>
    </customValue>
    <customValue>
        <fullName>Thu</fullName>
    </customValue>
    <customValue>
        <fullName>Fri</fullName>
    </customValue>
    <customValue>
        <fullName>Sat</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <masterLabel>Weekdays</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ClassSessionTriggerTest.cls
@isTest
public class ClassSessionTriggerTest {
@testSetup
    static void testDataSetup(){
        BlufyTestUtil.init();        
    }
    
    static testmethod void validateClassSessionTriggerTest(){
        Account tch  = [SELECT Name FROM Account WHERE recordtypeid =: ConstantClass.teacherRecordTypeId Limit 1];
        Account loc  = [Select Name from Account where recordtypeid =: ConstantClass.locationRecordsTypeId Limit 1];
        Class__c cls = [SELECT Name FROM Class__c LIMIT 1];
        Room__c room = [SELECT Name, Type__c, Location__c, Capacity__c FROM Room__c LIMIT 1];
        Session__c sessionObj = [SELECT Id, Name, Session_Date__c,Class__c, Class_Session__c, Room__c, Teacher__c FROM Session__c LIMIT 1];
        Class_Session__c clsSessObj = BlufyTestUtil.createClassSessionRec(cls.Id,Time.newInstance(10,30,00,00),'60');
        clsSessObj.Teacher__c       = tch.Id;
        clsSessObj.Room__c          = room.Id;
        clsSessObj.Day_of_Week__c   = 'Wed';
        insert clsSessObj;
        
        Account teacherObj = BlufyTestUtil.createTeacherRec('Marry', loc.Id);
        insert teacherObj;
        
        Room__c roomObj = BlufyTestUtil.createRoom(loc.Id, 'Room6', 'Group', 35);
        insert roomObj;
        
        sessionObj.Class_Session__c = clsSessObj.Id;
        update sessionObj;
        clsSessObj.Teacher__c = teacherObj.Id;
        clsSessObj.Room__c    = roomObj.Id;
        update clsSessObj;
        
        System.assertEquals(clsSessObj.Teacher__c, teacherObj.Id);
        
        DELETE clsSessObj;
    }
}