force-app/main/default/objects/Account/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/Payment_Account__c.object-meta.xml
<CustomObject>
    <label>Payment Account</label>
    <nameField>
        <displayFormat>PA-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payment Accounts</relationshipLabel>
    <relationshipName>Payment_Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <inlineHelpText>Only the last 4 digits will be visible.</inlineHelpText>
    <label>Account Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is used to activate the payment</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Holder_Name__c.field-meta.xml
<CustomField>
    <fullName>Holder_Name__c</fullName>
    <label>Holder Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_ID__c</fullName>
    <label>Stripe ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Stripe_Token__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Token__c</fullName>
    <label>Stripe Token</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to identify the type of Payment</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACH</fullName>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Account__c/fields/Verification_Status__c.field-meta.xml
<CustomField>
    <fullName>Verification_Status__c</fullName>
    <label>Verification Status</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Verified</fullName>
            </value>
            <value>
                <fullName>Not Verified</fullName>
            </value>
            <value>
                <fullName>Pass</fullName>
            </value>
            <value>
                <fullName>Fail</fullName>
            </value>
            <value>
                <fullName>Unchecked</fullName>
            </value>
            <value>
                <fullName>Unavailable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestPaymentAccountTrigger.cls
@isTest
public class TestPaymentAccountTrigger {
    @IsTest
    public static void TestAfterInsert(){
        Account accObj = new Account(LastName = 'Test Acc');
        insert accObj;
        Payment_Account__c paymentAccountObj = new Payment_Account__c();
        
        paymentAccountObj.Account_Number__c = '************4242';
        paymentAccountObj.Account__c = accObj.Id;
        paymentAccountObj.Active__c = true;
        paymentAccountObj.Holder_Name__c = 'Test Acc';
        paymentAccountObj.Stripe_ID__c = '';
        paymentAccountObj.Stripe_Token__c = '';
        paymentAccountObj.Type__c = 'Card'; 
        paymentAccountObj.Verification_Status__c = '';
        insert paymentAccountObj;
        Payment_Account__c paymentAccountObj1 = new Payment_Account__c();
        
        paymentAccountObj1.Account_Number__c = '************4343';
        paymentAccountObj1.Account__c = accObj.Id;
        paymentAccountObj1.Active__c = false;
        paymentAccountObj1.Holder_Name__c = 'Test Acc';
        paymentAccountObj1.Stripe_ID__c = '';
        paymentAccountObj1.Stripe_Token__c = '';
        paymentAccountObj1.Type__c = 'Card'; 
        paymentAccountObj1.Verification_Status__c = '';
        insert paymentAccountObj1;
        paymentAccountObj1.Active__c = true;
        update paymentAccountObj1;
        
    } 
}