force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Duration_in_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_in_Minutes__c</fullName>
    <label>Duration in Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c +  (Duration__c*60000)
/*IF(  ISPICKVAL(Duration_Unit__c, &apos;Minutes&apos;)  , educato__Start_Time__c +  (educato__Duration__c*60000) ,  educato__Start_Time__c +  (educato__Duration__c*3600000))*/</formula>
    <inlineHelpText>The system will calculate this field based on &apos;Duration Unit&apos; and &apos;Duration&apos;.</inlineHelpText>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <inlineHelpText>Start Time of this class on the days selected in &apos;Days of Week&apos;.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>&apos;Draft&apos; - For all newly created classes.
&apos;Open&apos; - Class published and accepting enrollments
&apos;Scheduled&apos; - Class with Term 1 sessions scheduled...</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Discontinued</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Class_Session__c/Class_Session__c.object-meta.xml
<CustomObject>
    <label>Class Session</label>
    <nameField>
        <displayFormat>CS-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Class Session</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Session__c/fields/Duration_In_Minutes__c.field-meta.xml
<CustomField>
    <fullName>Duration_In_Minutes__c</fullName>
    <label>Duration In Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Duration</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c + (VALUE(TEXT(Duration_In_Minutes__c)) * 60000)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Class_Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Class Session</relationshipLabel>
    <relationshipName>Class_Session</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Class_Term__c/Class_Term__c.object-meta.xml
<CustomObject>
    <label>Class Term</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Class Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class_Term__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
                <isActive>false</isActive>
                <label>Canceled</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
                <isActive>false</isActive>
                <label>In Progress</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Draft selected by default for a new Course.</description>
    <inlineHelpText>Activate or Deactivate a course. Deactivated Course will deactivate all its related classes.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <displayFormat>SE-{0000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <formula>Start_Time__c + (VALUE(TEXT(Duration_in_Minutes__c))*60000)
/*educato__Start_Time__c + (educato__Duration__c*60000)*/
/*IF( ISPICKVAL(educato__Duration_Unit__c, &apos;Minutes&apos;) , educato__Start_Time__c + (educato__Duration__c*60000) , educato__Start_Time__c+ (educato__Duration__c*3600000))*/</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <description>Date on which the Session will occur.</description>
    <inlineHelpText>Date on which the Session will occur.</inlineHelpText>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>Start Time of the Session.</description>
    <inlineHelpText>Start Time of the Session. The End Time of the Session will be updated based on Duration Unit and Duration.</inlineHelpText>
    <label>Start Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Session__c/Student_Session__c.object-meta.xml
<CustomObject>
    <label>Student Session</label>
    <nameField>
        <displayFormat>SS-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Student Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Student_Session__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Student Sessions</relationshipLabel>
    <relationshipName>Student_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Session__c/fields/Session_Date__c.field-meta.xml
<CustomField>
    <fullName>Session_Date__c</fullName>
    <formula>Session__r.Session_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Student_Session__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Attended</fullName>
            </value>
            <value>
                <fullName>Not Attended</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Leave__c/Teacher_Leave__c.object-meta.xml
<CustomObject>
    <label>Teacher Leave</label>
    <nameField>
        <displayFormat>TL-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Teacher Leaves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Teacher_Leave__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Requested</fullName>
                <default>true</default>
                <label>Requested</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Teacher_Leave__c/fields/Teacher__c.field-meta.xml
<CustomField>
    <fullName>Teacher__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Teacher</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.Name</field>
            <operation>equals</operation>
            <value>Teacher</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Teacher Leaves</relationshipLabel>
    <relationshipName>Teacher_Leaves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SessionService.cls
public class SessionService {
    
    //Get Sessions By Class Id
    public static List<Session__c> getSessionsByClassId(String classId){
        try{
            List<Session__c> listSession = [SELECT Id,Name,Session_Date__c,Start_Time__c,End_Time__c,Status__c,Teacher__c,Duration_in_Minutes__c,
                                            Teacher__r.Name,Type__c,Exception__c,Room__c,Room__r.Name,Sequence__c
                                            FROM Session__c WHERE Class__c =: classId 
                                            AND Status__c =: ConstantClass.ScheduledStatus WITH SECURITY_ENFORCED];
            return listSession;  
        }
        catch (System.QueryException e){
            System.debug('Error-->'+e.getMessage());
        }
        return null;
    }
    
    //Get Sessions By Class Id with Student Sessions
    public static List<Session__c> getSessionsByClassIdWithStudentSessions(Set<String> setClassId){
        try{
            if(!setClassId.isEmpty()){
                List<Session__c> listSession = [SELECT Id,Class__c,
                                                (SELECT Id FROM Student_Sessions__r)
                                                FROM Session__c WHERE Class__c IN : setClassId 
                                                AND Status__c =: ConstantClass.ScheduledStatus WITH SECURITY_ENFORCED];
                return listSession;    
            } 
        }
        catch(System.QueryException e){
            System.debug('Error-->'+e.getMessage());
        }
        return null;
    }
    
    //Insertion of Session Records
    public static List<Session__c> insertSessionRecords(List<Session__c> listSession){
        try{
            if(listSession.size() > 0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, listSession,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Session Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    insert securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        }
        catch(Exception e){
            System.debug('Session Error Message-->'+e.getMessage());
        }
        return null;
    }
    
    //updation of Session Records    
    public static List<Session__c> updateSessionRecords(List<Session__c> listSession){
        if(listSession.size() > 0){
            try{        
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPDATABLE, listSession,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Session Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    update securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
            
            catch(Exception e){
                System.debug('Session Error Message-->'+e.getMessage());
            }
        }
        return null;
    }
    
    //get of Session Records
    public static List<Session__c> getById(set<Id> sessionId){
        try{
            List<Session__c> listSession = [SELECT Id, Location__c,Teacher__c, Teacher__r.location__c,Session_Date__c,Start_Time__c,
                                            Class__r.Course__c,Class__r.Course__r.Name,Class__c,Notes__c, Type__c FROM Session__c WHERE id IN: sessionId
                                            WITH SECURITY_ENFORCED];
            return listSession;  
        }
        catch(System.QueryException e){
            System.debug(e.getMessage());
        }
        return null;         
    }
    
    public static List<Session__c> getSessionsByTeacherId(Set<String> setTeacherId){
        try{
            List<Session__c> listSession = [SELECT Id, Name, Status__c,Start_Time__c,End_Time__c,Session_Date__c,Teacher__c 
                                            FROM Session__c WHERE Teacher__c IN: setTeacherId AND Session_Date__c != null 
                                            AND Status__c = 'Scheduled' WITH SECURITY_ENFORCED];
            return listSession;  
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null; 
    }
    
    public static List<Session__c> getSessionsByRoomId(Set<String> setRoomId){
        try{
            List<Session__c> listSession = [SELECT Id, Name, Status__c,Start_Time__c,End_Time__c,Session_Date__c,Room__c 
                                            FROM Session__c WHERE Room__c IN: setRoomId AND Session_Date__c != null 
                                            AND Status__c = 'Scheduled' WITH SECURITY_ENFORCED];
            return listSession;  
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null; 
    }
    
    //Added by Rajesh on 31st July 2020, For session rollup on class
    public static List<AggregateResult> getSessionsAgreeByClassIds(Set<String> clsIds){
        try{
            List<String> excludeTypeList = new List<String>{ConstantClass.sessionType, ConstantClass.sessionIndividualType};
                return [SELECT Count(Id) sessionCount, Class__c, Status__c 
                        FROM Session__c WHERE Class__c IN: clsIds AND Type__c NOT IN:excludeTypeList WITH SECURITY_ENFORCED
                        GROUP BY Class__c, Status__c];  
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null; 
    }
    
    public static List<Session__c> getSessionsByTeacherLeave(Teacher_Leave__c teacherLeave){
        try{
            List<Session__c> listSession = [SELECT Id,Name,Session_Date__c,Start_Time__c,End_Time__c,Status__c,Teacher__c,
                                            Teacher__r.Name FROM Session__c WHERE Teacher__c =:teacherLeave.Teacher__c AND
                                            Status__c !=: ConstantClass.cancelledStatus AND Session_Date__c >=: teacherLeave.Start_Date__c
                                            AND Session_Date__c <=: teacherLeave.End_Date__c WITH SECURITY_ENFORCED
                                           ];
            return listSession;  
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null; 
    }
    
    public static List<Session__c> getByClassTermIdAlongWithEnrolDate(String classTermId,Date enrolDate){
        if(String.isNotBlank(classTermId) && enrolDate != NULL){
            try {
                List<Session__c> clasList = [SELECT Id, Name, Class__c, Sequence__c, Session_Date__c, Teacher__c, Status__c  
                                             FROM Session__c WHERE Class_Term__c =: classTermId AND 
                                             Status__c =: ConstantClass.scheduledStatus AND Session_Date__c >=: enrolDate
                                             WITH SECURITY_ENFORCED];
                
                return clasList;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    
    public static List<Session__c> getByClassTermIdAlongWithClassId(Set<String> setClassAndClassTermId){
        if(setClassAndClassTermId.size() > 0){
            try {
                List<Session__c> listSession = [SELECT Id, Name, Class__c, Class_Term__c, Sequence__c, Session_Date__c, Teacher__c, Status__c, 
                                                Class_Term__r.Name,Class_Term__r.Sequence__c, Class_Term__r.Start_Date__c, Class_Term__r.End_Date__c 
                                                FROM Session__c WHERE (Class__c IN: setClassAndClassTermId AND 
                                                                       Class_Term__c IN: setClassAndClassTermId ) 
                                                AND Class__c != null AND Session_Date__c >= TODAY 
                                                WITH SECURITY_ENFORCED ORDER BY Sequence__c ];
                
                return listSession;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    
    public static List<Session__c> getByClassSessionIdAlongWithEnrolDate(String classSessionId,Date enrolDate){
        List<Session__c> listSession = new List<Session__c>();
        try {
            if(String.isNotBlank(classSessionId) && enrolDate != NULL){
                Integer numOfMonthDays = Date.daysInMonth(enrolDate.year(),enrolDate.month());
                Date lstDateOfEnrolDateMonth = Date.newInstance(enrolDate.year(),enrolDate.month(),numOfMonthDays);
                listSession = [SELECT Id FROM Session__c WHERE Class_Session__c =: classSessionId AND 
                               Status__c =: ConstantClass.scheduledStatus AND Session_Date__c >=: enrolDate
                               AND Session_Date__c <=: lstDateOfEnrolDateMonth
                               WITH SECURITY_ENFORCED];
            }
        }catch (System.QueryException e) {
            System.debug(e.getMessage());
        }        
        return listSession;
    }
    
    public static List<Session__c> getSessionsByClassSessionId(Set<String> setClassSessionId){  
        try{
            if(setClassSessionId.size() > 0){
                List<Session__c> listSession = [SELECT Id,Name,Session_Date__c,Class__c,Class_Session__c FROM Session__c
                                                           WHERE Status__c =: ConstantClass.scheduledStatus 
                                                           AND Class_Session__c IN : setClassSessionId
                                                           WITH SECURITY_ENFORCED];
                return listSession;   
            }            
        }
        catch (System.QueryException e){
            System.debug(e.getMessage());
        }
        return null;    
    }
    
}