force-app/main/default/objects/Account/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>FIN #</fullName>
            </value>
            <value>
                <fullName>SSN</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/Class__c.object-meta.xml
<CustomObject>
    <label>Class</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Class__c/fields/Advance_Billing__c.field-meta.xml
<CustomField>
    <fullName>Advance_Billing__c</fullName>
    <label>Advance Billing Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <inlineHelpText>Links class to a course.</inlineHelpText>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Classes</relationshipLabel>
    <relationshipName>Classes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Days_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Days_of_Week__c</fullName>
    <label>Days of Week</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Weekdays</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>End Date of the class. End Date will be automatically updated when the sessions for this class are scheduled.</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Exclude_Public_Holidays__c.field-meta.xml
<CustomField>
    <fullName>Exclude_Public_Holidays__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclude Holidays</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Class__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>A Fixed class will have a defined number of session whereas an Ongoing class can have unlimited number of sessions.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Class__c/recordTypes/Class.recordType-meta.xml
<RecordType>
    <fullName>Class</fullName>
    <active>true</active>
    <label>Class</label>
</RecordType>

force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <description>A brief description of the course</description>
    <label>Course</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certificate</fullName>
            </value>
            <value>
                <fullName>Diploma</fullName>
            </value>
            <value>
                <fullName>IGCSE</fullName>
            </value>
            <value>
                <fullName>Bachelor&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Postgraduate</fullName>
            </value>
            <value>
                <fullName>Master&apos;s Degree</fullName>
            </value>
            <value>
                <fullName>Doctorate</fullName>
            </value>
            <value>
                <fullName>Short Professional Course</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course_Module__c/Course_Module__c.object-meta.xml
<CustomObject>
    <description>Course Modules.</description>
    <label>Course Module</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Course Modules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course_Module__c/fields/Course__c.field-meta.xml
<CustomField>
    <fullName>Course__c</fullName>
    <label>Course</label>
    <referenceTo>Course__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course_Module__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <label>Module</label>
    <referenceTo>Module__c</referenceTo>
    <relationshipLabel>Course Modules</relationshipLabel>
    <relationshipName>Course_Modules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Discount__c/Discount__c.object-meta.xml
<CustomObject>
    <label>Discount</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Discount__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Promo</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
            <value>
                <fullName>Referral</fullName>
            </value>
            <value>
                <fullName>Early Bird</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>E-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <referenceTo>Class__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Not using this</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Invoice_Label__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Label__c</fullName>
    <description>Fee label that appears on the Invoice.</description>
    <inlineHelpText>Fee label that appears on the Invoice.</inlineHelpText>
    <label>Invoice Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>to store due date of invoice</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>calculate from gross total and gst tax amount</description>
    <formula>Gross_Total__c  +  GST_Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/Invoice_Line_Item__c.object-meta.xml
<CustomObject>
    <description>for customer invoice line items(child records of invoice)</description>
    <label>Invoice Line Item</label>
    <nameField>
        <displayFormat>ILI-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>to store amount</description>
    <label>Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>store discount details</description>
    <label>Discount</label>
    <referenceTo>Discount__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>to store fee details</description>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <description>to store related invoice details</description>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Line Items</relationshipLabel>
    <relationshipName>Invoice_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line_Item__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>type of invoice line item</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fee</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Discount</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Weekdays.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Mon</fullName>
    </customValue>
    <customValue>
        <fullName>Tue</fullName>
    </customValue>
    <customValue>
        <fullName>Wed</fullName>
    </customValue>
    <customValue>
        <fullName>Thu</fullName>
    </customValue>
    <customValue>
        <fullName>Fri</fullName>
    </customValue>
    <customValue>
        <fullName>Sat</fullName>
    </customValue>
    <customValue>
        <fullName>Sun</fullName>
    </customValue>
    <masterLabel>Weekdays</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestStripeCustomerPaymentBatch.cls
@isTest
private class TestStripeCustomerPaymentBatch {
    @testSetup  
    static void testSetUp(){
        Account locationObj = BlufyTestUtil.createLocationRec('New Harbor');
        insert locationObj;
        system.debug('locationObj -> '+locationObj);
        
        
        Account parentObj = BlufyTestUtil.createParentRec('Gates','test1@gmail.com');
        insert parentObj;
        system.debug('parentObj ->'+parentObj);
        
        Account teacherObj = BlufyTestUtil.createTeacherRec('Jonas', locationObj.id);
        insert teacherObj;
        system.debug('teacherObj ->'+teacherObj);
        
        Course__c courseObj = BlufyTestUtil.createCourseRec('French', 'Active','XYZ-01');
        insert courseObj;
        system.debug('courseObj ->'+courseObj);
        
        Module__c module = BlufyTestUtil.createModule('Module 1');
        insert module;
        
        Course_Module__c cModule = BlufyTestUtil.createCourseModule(module.Id,courseObj.Id,1);
        insert cModule;
        
        Class__c classObj = BlufyTestUtil.createClassRec('Name', courseObj.Id, 'Classroom', 'Open', teacherObj.Id, 20, 'Fixed', 24, Date.today().addDays(1), Time.newInstance(10, 00, 00, 00),'One-time', cModule.Id);
        classObj.Advance_Billing__c         = 2;
        classObj.Days_of_Week__c            = 'Fri;Mon;Tue;Wed;Sat;Thu;Sun';
        classObj.End_Date__c                = Date.today().addMonths(6);
        classObj.Exclude_Public_Holidays__c = true;
        insert classObj;
        system.debug('classObj ->'+classObj);
        
        Account studentObj = BlufyTestUtil.createStudentRec('Thomas','test1@gmail.com');
        insert studentObj;
        system.debug('studentObj ->'+studentObj);
       
        Enrollment__c enrollObj = BlufyTestUtil.createEnrollment(classObj.Id, Date.today().addDays(-4), locationObj.Id, studentObj.Id, ConstantClass.enrolledStatus, true,  Date.today().addDays(-4),parentObj.id);
        insert enrollObj;
     
        Fee__c feeObj = BlufyTestUtil.createFeeRecords('Math Monthly Fee','Tuition Fee',500,true,true,'Ongoing','Monthly',2,90);
        feeObj.Invoice_Label__c = 'Test';
        insert feeObj;
        
        Discount__c discount = BlufyTestUtil.createDiscount('testing','Discount',Date.today().addDays(1),Date.today().addMonths(1),'Active','Amount',500,true);
        insert discount;
        
         
        Invoice__c invoiceObj = BlufyTestUtil.createInvoice(parentObj.Id,ConstantClass.dueStatus,Date.today());
        insert invoiceObj;
        
        invoiceObj.Due_Date__c = System.today().addDays(-2);
        
        
         
        
        Invoice_Line_Item__c invLinItm = new   Invoice_Line_Item__c(Invoice__c = invoiceObj.Id,Enrollment__c = enrollObj.Id,Type__c = ConstantClass.depositFeeType,Amount__c = 150);    
        invLinItm.educato__Fee__c = feeObj.id;
        invLinItm.educato__Discount__c = discount.id;
        invLinItm.educato__GST_Amount__c = 100;
        insert invLinItm;
        
        
        Invoice_Line_Item__c invLinItm1 = new   Invoice_Line_Item__c(Invoice__c = invoiceObj.Id,Enrollment__c = enrollObj.Id,Type__c = ConstantClass.depositFeeType,Amount__c = 150);    
        invLinItm1.educato__Fee__c = feeObj.id;
        invLinItm1.educato__Discount__c = discount.id;
        invLinItm1.educato__GST_Amount__c = 100;
        insert invLinItm1;
        System.debug('Result : ' + [Select Id, Total_Amount__c,Customer__c,Due_Date__c,Status__c,Automation_Applied__c,educato__GST_Tax_Amount__c,educato__Fee_Amount__c,educato__Discount_Amount__c,educato__Deposit_Amount__c   from Invoice__c where Id = :invoiceObj.Id]);
        System.debug('invoiceObj Customer__c---->'+invoiceObj.Customer__c);
        System.debug('invoiceObj Total_Amount__c---->'+invoiceObj.Total_Amount__c);
        System.debug('invoiceObj Due_Date__c---->'+invoiceObj.Due_Date__c);
        System.debug('invoiceObj Status__c---->'+invoiceObj.Status__c);
        System.debug('invoiceObj Automation_Applied__c---->'+invoiceObj.Automation_Applied__c);
        System.debug('invoiceObj educato__GST_Tax_Amount__c---->'+invoiceObj.educato__GST_Tax_Amount__c);
        System.debug('invoiceObj educato__Fee_Amount__c---->'+invoiceObj.educato__Fee_Amount__c);
        System.debug('invoiceObj educato__Discount_Amount__c---->'+invoiceObj.educato__Discount_Amount__c);    
        System.debug('invoiceObj educato__Deposit_Amount__c---->'+invoiceObj.educato__Deposit_Amount__c);  
        
    }
    
    @isTest
    static void test1(){
        test.startTest();
        Set<Id> setOfAccountIds = new Set<Id>();
        Invoice__c  invoiceObj = [Select Id, Total_Amount__c,Customer__c,Due_Date__c,Status__c,Automation_Applied__c,educato__GST_Tax_Amount__c,educato__Fee_Amount__c,educato__Discount_Amount__c,educato__Deposit_Amount__c   from Invoice__c  limit 1];
        Account accObj = [Select id from account where name ='Gates' limit 1];
        setOfAccountIds.add(accObj.id);
        StripeCustomerPaymentBatch  objBatch = new StripeCustomerPaymentBatch (setOfAccountIds);
        Database.executeBatch(objBatch);
        
        Test.setMock(HttpCalloutMock.class, new StrpeUtilityMock());
      /*  StripeCustomerPaymentScheduler sh1 = new StripeCustomerPaymentScheduler(); 
        String sch = '0 0 23 * * ?';
        system.schedule('Test StripeCustomerPaymentScheduler Check', sch, sh1);
*/
        test.stopTest();
    }
    
    
}