force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <description>For Manage relationship</description>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Account_2__c.field-meta.xml
<CustomField>
    <fullName>Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family (Account 2)</relationshipLabel>
    <relationshipName>Family1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family</relationshipLabel>
    <relationshipName>Family</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FamilyTriggerHandlerTest.cls
@isTest
public class FamilyTriggerHandlerTest {
    static testmethod void validateFamilyTriggerHandler(){
        Account parObj = new Account(recordtypeid = ConstantClass.customerRecTypeId, LastName = 'Parent Test');
        insert parObj;
        Account stuObj = new Account(recordtypeid = ConstantClass.studCustomerRecordTypeId, LastName = 'Student Test');
        insert stuObj;
        Family__c fmly = new Family__c(Name = 'Test', Account__c = parObj.Id, Account_2__c = stuObj.Id,
                                       Relationship__c = ConstantClass.childFmlyRelationPicklist);
        insert fmly;
        
        Family__c recFmly = [SELECT Name, Account__c, Account_2__c, Relationship__c 
                             FROM Family__c 
                             WHERE Account__c =: stuObj.Id 
                             LIMIT 1];
        
        System.assertEquals(recFmly.Account__c, fmly.Account_2__c);
    }
}