force-app/main/default/objects/Family__c/Family__c.object-meta.xml
<CustomObject>
    <description>For Manage relationship</description>
    <label>Family</label>
    <nameField>
        <label>Family Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Family</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Family__c/fields/Account_2__c.field-meta.xml
<CustomField>
    <fullName>Account_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family (Account 2)</relationshipLabel>
    <relationshipName>Family1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Family</relationshipLabel>
    <relationshipName>Family</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Family__c/fields/Relationship__c.field-meta.xml
<CustomField>
    <fullName>Relationship__c</fullName>
    <label>Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spouse</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Child</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FamilyTriggerHandler.cls
public class FamilyTriggerHandler {
    public static Boolean isStopRecursion = true; // used to stop trigger for calling recursively
    public static void createReciprocalFamilyRecord(List<Family__c> fmlyList){
        List<Family__c> insertRecpFmlyRecord = new List<Family__c>();
        for(Family__c fmly : fmlyList){
            if(fmly.Relationship__c == ConstantClass.parentFmlyRelationPicklist){
                Family__c fam = new Family__c(Name            = fmly.Name,
                                              Account_2__c    = fmly.Account__c,
                                              Account__c      = fmly.Account_2__c,
                                              Relationship__c = ConstantClass.childFmlyRelationPicklist);
                insertRecpFmlyRecord.add(fam);
            }
            
            if(fmly.Relationship__c == ConstantClass.childFmlyRelationPicklist){
                Family__c fam = new Family__c(Name            = fmly.Name,
                                              Account_2__c    = fmly.Account__c,
                                              Account__c      = fmly.Account_2__c,
                                              Relationship__c = ConstantClass.parentFmlyRelationPicklist);
                insertRecpFmlyRecord.add(fam);
            }
            
            if(fmly.Relationship__c == ConstantClass.spouseFmlyRelationPicklist || 
               fmly.Relationship__c == ConstantClass.siblingFmlyRelationPicklist){
                   Family__c fam = new Family__c(Name            = fmly.Name,
                                                 Account_2__c    = fmly.Account__c,
                                                 Account__c      = fmly.Account_2__c,
                                                 Relationship__c = fmly.Relationship__c);
                   insertRecpFmlyRecord.add(fam);
               }
        }
        
        if(insertRecpFmlyRecord.size() > 0){
            FamilyService.insertRecords(insertRecpFmlyRecord);
        }
    }
}