force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Automation_Applied__c.field-meta.xml
<CustomField>
    <fullName>Automation_Applied__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation Applied</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <description>to store account details if record type is customer</description>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Business_Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoice (Customer)</relationshipLabel>
    <relationshipName>Invoice_Customer</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Due_Date__c.field-meta.xml
<CustomField>
    <fullName>Due_Date__c</fullName>
    <description>to store due date of invoice</description>
    <label>Due Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount__c</fullName>
    <description>calculate from gross total and gst tax amount</description>
    <formula>Gross_Total__c  +  GST_Tax_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/StripePaymentBatch.cls
/* Name         : StripePaymentBatch
 * Date         : 10th Dec 2020
 * Author       : 
 * Description  : This batch class is for creating charge Payments against the invoices which are due and any of the payment mode is not successfull.
**/
global without sharing class StripePaymentBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts{
    global Set<Id> setAccountIds;
    global StripePaymentBatch(){
        System.debug('JM :: StripePaymentBatch non parameterized constructor called');
        setAccountIds = null;
    }
    global StripePaymentBatch(Set<id> setAccountIds){
        System.debug('JM :: StripePaymentBatch parameterized constructor called');
        this.setAccountIds = new Set<Id>();
        this.setAccountIds.addAll(setAccountIds);
    }
    global Database.QueryLocator start(Database.BatchableContext BC){
        System.debug('StripePaymentBatch start method called');
        String query;
        // if(this.setAccountIds == null)
        //     query = 'Select Id, Customer__c, Total_Amount__c, (Select Id, educato__Status__c from educato__Payments__r) FROM Invoice__c WHERE Customer__c != NULL AND Due_Date__c <= today() AND Status__c= \'Due\' AND Total_Amount__c > 0 AND Automation_Applied__c = FALSE WITH SECURITY_ENFORCED';
        // else
        //     query = 'Select Id, Customer__c, Total_Amount__c, (Select Id, educato__Status__c from educato__Payments__r) FROM Invoice__c WHERE Customer__c != NULL AND Due_Date__c <= today() AND Status__c= \'Due\' AND Total_Amount__c > 0 AND Customer__c IN :this.setAccountIds AND Automation_Applied__c = FALSE WITH SECURITY_ENFORCED';
        
        if(this.setAccountIds == null)
            query = 'Select Id, Customer__c, Total_Amount__c, Automation_Applied__c, (Select Id, educato__Status__c from educato__Payments__r) FROM Invoice__c WHERE Customer__c != NULL AND Status__c= \'Due\' AND Total_Amount__c > 0 AND Automation_Applied__c = FALSE WITH SECURITY_ENFORCED';
        else
            query = 'Select Id, Customer__c, Total_Amount__c, Automation_Applied__c, (Select Id, educato__Status__c from educato__Payments__r) FROM Invoice__c WHERE Customer__c != NULL AND Status__c= \'Due\' AND Total_Amount__c > 0 AND Customer__c IN :setAccountIds AND Automation_Applied__c = FALSE WITH SECURITY_ENFORCED';
        
        //System.debug('Database.getQueryLocator(query)--->'+Database.getQueryLocator(query));
        System.debug('JM :: Query : '+query);
        
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Invoice__c> lstInvoices){
        System.debug('JM :: StripeCustomerPaymentBatch execute method is called');
        StripePaymentBatchHelper.getCustomerChargeDetails(lstInvoices);
    }
    global void finish(Database.BatchableContext BC){
        System.debug('JM :: StripeCustomerPaymentBatch finish method called');
    }
}