force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transaction</fullName>
                <default>true</default>
                <label>Transaction</label>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Log__c/Payment_Log__c.object-meta.xml
<CustomObject>
    <label>Payment Log</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>Payment Log Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment_Log__c/fields/Charge_Id__c.field-meta.xml
<CustomField>
    <fullName>Charge_Id__c</fullName>
    <externalId>true</externalId>
    <label>Charge Id</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Invoice__c.field-meta.xml
<CustomField>
    <fullName>Invoice__c</fullName>
    <label>Invoice</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Payment Logs</relationshipLabel>
    <relationshipName>Payment_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failure</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
                <isActive>false</isActive>
                <label>Pending</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/StripeACHChargesVerificationBatchHelper.cls
public class StripeACHChargesVerificationBatchHelper {
    public StripeACHChargesVerificationBatchHelper() {

    }
    public static void getUpdateChargesStatus(List<Payment__c> lstPayments){
        List<Payment_Log__c> lstNewPaymentLogs = new List<Payment_Log__c>(); 
        List<Payment__c> lstUpdatePayments = new List<Payment__c>();
        List<Invoice__c> lstUpdatedInvoices = new List<Invoice__c>();
        for(Payment__c obj : lstPayments){
            HttpResponse resp = StripeUtility.getUpdatedCharges(obj.Payment_Reference__c);
            if(resp != null){
                String status = null;
                if(resp.getStatusCode() == 200){
                    status = (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('status');
                    lstNewPaymentLogs.add(new Payment_Log__c(Charge_Id__c = (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('id'),
                                                                        Invoice__c = obj.Invoice__c, 
                                                                        Status__c = status.compareTo('succeeded')==0 || status.compareTo('pending')==0 ? 'Success':'Failure', 
                                                                        Message__c = status.compareTo('succeeded')==0 ? 'Payment Successful.' : status.compareTo('pending')==0 ? 'Payment is Pending.' : (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_message') ,
                                                                        //Code__c = status.compareTo('succeeded')==0 || status.compareTo('pending')==0 ? '200': (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_code'),
                                                                        //Code__c will be containing the details only incase of failed
                                                                        Code__c = status.compareTo('failed')==0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_code') : '',
                                                                        Type__c= status.compareTo('succeeded')==0 || status.compareTo('pending')==0 ? 'OK' : 'Failed' 
                                                                ));
                    if(status.compareTo('succeeded')==0)
                        lstUpdatedInvoices.add(new Invoice__c(Id = obj.Invoice__c, Status__c = 'Paid'));
                }
                else{
                    lstNewPaymentLogs.add(new Payment_Log__c(
                                                                Invoice__c = obj.Id, 
                                                                Status__c= 'Failure', 
                                                                Message__c = (String)((Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('error')))).get('message'), 
                                                                Code__c = String.valueOf(resp.getStatusCode()), 
                                                                Type__c= (String)((Map<String,Object>)JSON.deserializeUntyped(JSON.serialize(((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('error')))).get('type')
                                                            ));

                }
                lstUpdatePayments.add(new Payment__c(
                                                        Id = obj.Id, 
                                                        Status__c = status.compareTo('succeeded') == 0 ? 'Success' : status.compareTo('pending') == 0 ? 'Pending' : 'Failed',
                                                        Comments__c = status.compareTo('succeeded') == 0 ? 'Payment Successful.' : status.compareTo('failed') == 0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_message') : status.compareTo('pending') == 0 ? 'Status is Pending.' : ''
                                                    ));
                // lstUpdatePayments.add(new Payment__c(Id = obj.Id, Status__c = status.compareTo('succeeded')==0? 'Success' : status.compareTo('pending')==0 ? 'Pending' : 'Failed', 
                //                                         //Comments__c = status.compareTo('succeeded')==0? 'Payment Successful.' : status.compareTo('failed') == 0 ? (String) ((Map<String,Object>)JSON.deserializeUntyped(resp.getBody())).get('failure_message') : status.compareTo('pending') == 0 ? 'Status is Pending.' : null,
                                                    
                //     ));
            }
        }
        if(lstNewPaymentLogs.size()>0){
            System.debug('JM :: Going to insert Payment Logs');
            insert lstNewPaymentLogs;
        }
        if(lstUpdatePayments.size()>0){
            System.debug('JM :: Going to update Payment Records');
            update lstUpdatePayments;
        }
        if(lstUpdatedInvoices.size()>0){
            System.debug('JM :: Going to update Invoice records');
            update lstUpdatedInvoices;
        }
    }
}