force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Transaction</fullName>
                <default>true</default>
                <label>Transaction</label>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PaymentService.cls
public class PaymentService {
    
    public static List<AggregateResult> getPaymentByAggResult(Set<String> setInvoiceId){
        if(!setInvoiceId.isEmpty()){
            try {
                List<AggregateResult> listPayment = [SELECT SUM(AMOUNT__C) totalAmount,Type__c,Invoice__c FROM Payment__c 
                                                     WHERE Invoice__c IN: setInvoiceId 
                                                     AND Type__c != NULL AND Status__c IN ('paid','Success') 
                                                     WITH SECURITY_ENFORCED
                                                     GROUP BY Invoice__c, Type__c];
                
                return listPayment;
            }catch (System.QueryException e) {
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    //Insertion of Payment Records
    public static List<Payment__c> insertPaymentRecords(List<Payment__c> listPayment){
        try{
            if(listPayment.size() > 0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, listPayment,true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Payment Removed Fields-->'+securityDecision.getRemovedFields());
                }
                else{
                    insert securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        }
        catch(Exception e){
            System.debug('Payment Error Message-->'+e.getMessage());
        }
        return null;
    }
    /**
     * Created By   : Jatin Motiani
     * Date         : 04th Jan 2021
     * Description  : To update the Payment__c object Records 
     */
    public static List<Payment__c> updatePaymentRecords(List<Payment__c> lstPayments){
        try {
            if(lstPayments.size()>0){
                SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.UPDATABLE, lstPayments, true);
                if(securityDecision.getRemovedFields().keySet().size() > 0){
                    System.debug('Error :: Payment Removed Fields :: '+securityDecision.getRemovedFields());
                }
                else{
                    UPDATE securityDecision.getRecords();
                    return securityDecision.getRecords();
                }
            }
        } catch (Exception e) {
            System.debug('Payment Error Message :: '+e.getMessage());
        }
        return null;
    }
}