force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>for customer invoice</description>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{00000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>to store status of invoice</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Due</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Overdue</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Void</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>PAY-{000000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Payment_Mode__c.field-meta.xml
<CustomField>
    <fullName>Payment_Mode__c</fullName>
    <label>Payment Mode</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cash</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Credit Card</fullName>
            </value>
            <value>
                <fullName>Credit Note</fullName>
            </value>
            <value>
                <fullName>GIRO</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Wire Transfer</fullName>
            </value>
            <value>
                <fullName>ACH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StripeChargeVerifyBatch.cls
/* Name         : StripeChargeVerifyBatch
* Date         : 14th Dec 2020
* Author       : 
* Description  : This batch class will be verifing the status of charges created against the invoices in the Stripe.
**/
global without sharing class StripeChargeVerifyBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
    global String paymentId;
    global StripeChargeVerifyBatch() {
    }
    global StripeChargeVerifyBatch(String paymentId) {
        this.paymentId = paymentId;
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        Date transactionDate = System.today().addDays(-7);
        /*String query = 'SELECT Payment_Date__c, Status__c, Invoice__c, Invoice__r.Status__c, Amount__c,Payment_Reference__c ' +
'FROM Payment__c '+
'WHERE Payment_Date__c <= :transactionDate ' +
'AND (Status__c = \'Pending\' OR Status__c = \'Failed\') '+
'AND Payment_Mode__c =\'ACH\' WITH SECURITY_ENFORCED';
*/
        
        if (String.isNotBlank(this.paymentId)){
            String query = 'SELECT Payment_Date__c, Status__c, Invoice__c, Invoice__r.Status__c, Amount__c,Payment_Reference__c '+
                'FROM Payment__c '+
                'WHERE Id = :paymentId ' +
                'AND (Status__c = \'Pending\' OR Status__c = \'Failed\') '+
                'AND Payment_Mode__c =\'ACH\' WITH SECURITY_ENFORCED';
            
            return Database.getQueryLocator(query);    
        }
        else{
            String query = 'SELECT Payment_Date__c, Status__c, Invoice__c, Invoice__r.Status__c, Amount__c,Payment_Reference__c '+
                'FROM Payment__c '+
                'WHERE (Status__c = \'Pending\' OR Status__c = \'Failed\') '+
                'AND Payment_Mode__c =\'ACH\' WITH SECURITY_ENFORCED';
            
            return Database.getQueryLocator(query);
        }
        
    }
    global void execute(Database.BatchableContext BC, List<Payment__c> lstPayments){
        StripeChargeVerifyBatchHelper.getUpdateChargesStatus(lstPayments);
    }
    global void finish(Database.BatchableContext BC){
        
    }
    
}