force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <label>Fee</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Schedule__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/GST_Applicable__c.field-meta.xml
<CustomField>
    <fullName>GST_Applicable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Applies GST if checked.</description>
    <inlineHelpText>Applies GST if checked.</inlineHelpText>
    <label>GST Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Override__c.field-meta.xml
<CustomField>
    <fullName>Override__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>When checked, it allows the user to remove the Fee at enrollment.</inlineHelpText>
    <label>Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Refer to a parent fee record</description>
    <inlineHelpText>Select a parent fee record</inlineHelpText>
    <label>Parent</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Fee__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Primary</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Fee__c</referenceTo>
    <relationshipLabel>Related Fees</relationshipLabel>
    <relationshipName>Related_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Prorate__c.field-meta.xml
<CustomField>
    <fullName>Prorate__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Applicable only for tuition fee.</inlineHelpText>
    <label>Prorate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The Fee will be applied (checked) by default at the time of enrollment. The Override field can used used to allow user to remove (uncheck) the Fee.</description>
    <inlineHelpText>The Fee will be applied (checked) by default at the time of enrollment. The Override field can used used to allow the user to remove (uncheck) the Fee.</inlineHelpText>
    <label>Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
            </value>
            <value>
                <fullName>Ongoing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Tuition Fee</fullName>
            </value>
            <value>
                <fullName>Other Fee</fullName>
            </value>
            <value>
                <fullName>Deposit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <description>Price Per Session.</description>
    <inlineHelpText>Price Per Session.</inlineHelpText>
    <label>Unit Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Units__c.field-meta.xml
<CustomField>
    <fullName>Units__c</fullName>
    <label>Number of Units</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fee__c/recordTypes/Secondary.recordType-meta.xml
<RecordType>
    <fullName>Secondary</fullName>
    <active>true</active>
    <description>Refers to a child record</description>
    <label>Secondary</label>
</RecordType>

force-app/main/default/globalValueSets/Frequency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Term</fullName>
    </customValue>
    <customValue>
        <fullName>One_Time</fullName>
        <label>One-Time</label>
    </customValue>
    <customValue>
        <fullName>Bi-Weekly</fullName>
        <isActive>false</isActive>
        <label>Bi-Weekly</label>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
        <isActive>false</isActive>
        <label>One-Time</label>
    </customValue>
    <masterLabel>Frequency</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/FeeService.cls
public class FeeService{
	
    public static List<Fee__c> getFeeById(String feeId){
        if(String.isNotBlank(feeId)){
            try {
                List<Fee__c> listFee = [SELECT Id, Name, Amount__c, Units__c, Unit_Price__c, Frequency__c, Schedule__c 
                                        FROM Fee__c WHERE Id =: feeId AND Amount__c > 0 AND  Unit_Price__c != null AND 
                                        Prorate__c = true WITH SECURITY_ENFORCED];
                
                return listFee;
            }catch(System.QueryException e){
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
    
    public static List<Fee__c> getRelatedFeeById(String feeId){
        if(String.isNotBlank(feeId)){
            try {
                List<Fee__c> listFee = [SELECT Id, Name, Type__c, Frequency__c, Amount__c, Schedule__c, Units__c, Unit_Price__c,Parent__c,
                                        Override__c,Required__c,GST_Applicable__c FROM Fee__c WHERE Parent__c =: feeId  AND 
                                        RecordType.Name = 'Secondary' WITH SECURITY_ENFORCED];
                
                return listFee;
            }catch(System.QueryException e){
                System.debug(e.getMessage());
            }        
        }
        return null;
    }
}